"""
Strategy Library — browse and filter the catalog of available strategies.

GET /api/strategy-library   — filterable, sortable catalog of all strategies.
                              Returns in-memory data (DB migration pending).
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Query

from app.dependencies import get_current_user
from app.db.models.users import User

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/strategy-library", tags=["strategy-library"])

# ---------------------------------------------------------------------------
# Hardcoded catalog (42 strategies).  Will be migrated to DB query once
# the strategy_meta table is seeded.
# ---------------------------------------------------------------------------

CATALOG: List[Dict[str, Any]] = [
    {
        "id": 1,
        "module_name": "orb_stocks_in_play",
        "display_name": "ORB Stocks-in-Play",
        "tagline": "5-min opening range breakout on stocks with >100% relative volume",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 2.81,
        "win_rate_pub": 0.60,
        "max_dd_pub": -0.12,
        "decay_risk": "low",
        "source_url": "https://ssrn.com/abstract=4729284",
        "paper_citation": "SSRN 4729284",
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Buy stocks that gap up and break their first 5-minute high on above-average volume. Exit at day-end or stop.",
        "mechanics_md": "Entry: 5-min ORB breakout above first 5-min high with RVOL > 100%. Stop: 2× ATR below entry. Target: 1.5× range.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 2,
        "module_name": "time_series_momentum_etf",
        "display_name": "Time-Series Momentum (ETF)",
        "tagline": "If 12-month return > 0, stay long. If negative, exit.",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "position",
        "difficulty": "beginner",
        "risk_profile": "standard",
        "published_sharpe": 1.1,
        "win_rate_pub": None,
        "max_dd_pub": -0.15,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": True,
        "popularity_score": 0.0,
        "description_md": "Simple trend-following: if the asset is up over the past 12 months, hold it. Otherwise exit to cash.",
        "mechanics_md": "Monthly check: if 12-month total return > 0, buy/hold. If < 0, sell. Rebalance monthly.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 3,
        "module_name": "wheel_strategy",
        "display_name": "The Wheel",
        "tagline": "Sell cash-secured puts, then covered calls after assignment",
        "category": "Options Income",
        "asset_class": "options",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "conservative",
        "published_sharpe": None,
        "win_rate_pub": 0.72,
        "max_dd_pub": -0.20,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "Practitioner",
        "suggested_bot": "options_income",
        "data_feed": "free_alpaca",
        "is_top_pick": True,
        "popularity_score": 0.0,
        "description_md": "Repeatedly sell puts on stocks you'd like to own. If assigned, sell covered calls until called away.",
        "mechanics_md": "Step 1: Sell 30-DTE 5-8% OTM cash-secured put. Step 2: If assigned, sell 30-DTE ATM-to-slightly-OTM covered call. Repeat.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 4,
        "module_name": "dual_momentum_gem",
        "display_name": "Dual Momentum (GEM)",
        "tagline": "Combine absolute and relative momentum to rotate between US stocks, international stocks, and bonds",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "position",
        "difficulty": "beginner",
        "risk_profile": "standard",
        "published_sharpe": 1.22,
        "win_rate_pub": None,
        "max_dd_pub": -0.17,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=2042750",
        "paper_citation": "Antonacci (2012)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": True,
        "popularity_score": 0.0,
        "description_md": "Gary Antonacci's Global Equities Momentum: rotate monthly between SPY, EFA, and AGG based on 12-month momentum signals.",
        "mechanics_md": "Step 1: If SPY 12-month return > T-bill rate (absolute momentum), enter equities. Step 2: If SPY > EFA (relative momentum), hold SPY; else hold EFA. Step 3: If absolute momentum fails, hold AGG.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 5,
        "module_name": "minervini_trend_template_filter",
        "display_name": "Minervini Trend Template",
        "tagline": "8-criteria filter to identify stocks in Stage 2 uptrends with institutional sponsorship",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.8,
        "win_rate_pub": 0.50,
        "max_dd_pub": -0.10,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "Minervini (2013)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Mark Minervini's SEPA methodology: buy only stocks meeting all 8 trend template criteria — price above 150/200 MA, 200 MA trending up, etc.",
        "mechanics_md": "Filter: price > 150-day MA > 200-day MA (trending up at least 1 month); price > 50-day MA; price within 25% of 52-week high; price at least 30% above 52-week low; RS rating ≥ 70.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 6,
        "module_name": "weinstein_stage2_breakout",
        "display_name": "Weinstein Stage 2 Breakout",
        "tagline": "Buy stocks emerging from a base into Stage 2 on above-average volume",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "position",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.5,
        "win_rate_pub": 0.55,
        "max_dd_pub": -0.12,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "Weinstein (1988)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Stan Weinstein's stage analysis: enter stocks that break out of a Stage 1 base into Stage 2 on 2× average weekly volume.",
        "mechanics_md": "Stage 2 criteria: price breaks above 30-week MA with rising MA; volume spike on breakout week ≥ 2× 10-week average. Stop: below 30-week MA or base low.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 7,
        "module_name": "cup_handle_breakout",
        "display_name": "Cup-and-Handle Breakout",
        "tagline": "Classic CANSLIM-style base breakout on high volume",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.65,
        "win_rate_pub": 0.52,
        "max_dd_pub": -0.10,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "O'Neil (1988)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "William O'Neil's cup-and-handle pattern: buy when price breaks out of the handle pivot on volume ≥ 40% above average.",
        "mechanics_md": "Cup depth 15-33%. Handle: price pulls back ≤ 15% from cup high, forms orderly shelf. Entry: pivot breakout with volume surge. Stop: below handle low.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 8,
        "module_name": "bull_put_credit_spread",
        "display_name": "Bull Put Credit Spread",
        "tagline": "Sell OTM put spread on bullish or neutral stocks to collect premium",
        "category": "Options Income",
        "asset_class": "options",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "conservative",
        "published_sharpe": None,
        "win_rate_pub": 0.75,
        "max_dd_pub": -0.08,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "Practitioner",
        "suggested_bot": "options_income",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Sell a lower put, buy an even lower put for protection. Profit if stock stays above short strike at expiration.",
        "mechanics_md": "Entry: sell 30-DTE put at 20-delta, buy put 5 strikes lower. Target: 50% of max profit. Stop: 200% of premium collected. Avoid before earnings.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 9,
        "module_name": "gap_and_go_momentum",
        "display_name": "Gap-and-Go Momentum",
        "tagline": "Buy stocks gapping up with news catalyst on the open",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "advanced",
        "risk_profile": "aggressive",
        "published_sharpe": 2.1,
        "win_rate_pub": 0.55,
        "max_dd_pub": -0.15,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": "Practitioner",
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Capture continuation momentum on stocks with a significant gap and confirmed news catalyst. Enter on first 1-min candle close above the high of the opening candle.",
        "mechanics_md": "Entry: gap > 4%, news catalyst confirmed, first 1-min close above opening candle high. Size: 2% account risk. Stop: below opening candle low. Target: 2:1 RR.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 10,
        "module_name": "raschke_holy_grail",
        "display_name": "Raschke Holy Grail",
        "tagline": "Pullback to 20-day EMA in a strong ADX trend, enter on bounce",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.45,
        "win_rate_pub": 0.58,
        "max_dd_pub": -0.09,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "Raschke & Connors (1995)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Linda Raschke's setup: when ADX is above 30 and the price pulls back to the 20-day EMA, buy the first up day.",
        "mechanics_md": "Filter: ADX(14) > 30, price in uptrend. Setup: price pulls back to 20-day EMA. Entry: buy on close of first up day touching or near the EMA. Stop: below the pullback low. Target: new highs.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 11,
        "module_name": "intraday_momentum_noise_band",
        "display_name": "Intraday Momentum Noise Band",
        "tagline": "Trade breakouts from intraday noise bands using adaptive volatility channels",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "advanced",
        "risk_profile": "standard",
        "published_sharpe": 1.9,
        "win_rate_pub": 0.52,
        "max_dd_pub": -0.13,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Identify and trade breakouts beyond adaptive intraday noise bands calibrated to recent volatility.",
        "mechanics_md": "Compute 20-period intraday ATR. Set bands at ±1.5× ATR from VWAP. Trade breakout direction when price closes beyond band with volume confirmation.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 12,
        "module_name": "heston_half_hour_continuation",
        "display_name": "Heston Half-Hour Continuation",
        "tagline": "Follow the dominant half-hour trend into the afternoon session",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.75,
        "win_rate_pub": 0.54,
        "max_dd_pub": -0.11,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "The direction of the first 30-minute session tends to persist into the afternoon. Take a position in that direction after a brief midday consolidation.",
        "mechanics_md": "Identify first 30-min trend direction. Wait for midday consolidation (10:30–12:30). Enter on breakout continuation after 12:30. Exit by 3:45.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 13,
        "module_name": "vwap_reversion_chop",
        "display_name": "VWAP Reversion in Chop",
        "tagline": "Fade moves away from VWAP when market is in a non-trending regime",
        "category": "Mean Reversion",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.55,
        "win_rate_pub": 0.62,
        "max_dd_pub": -0.09,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "In choppy, range-bound markets, price tends to revert to VWAP. Fade extensions beyond 1.5× ATR from VWAP.",
        "mechanics_md": "Regime filter: ADX < 20 (chop). Entry: price moves > 1.5× 30-min ATR from VWAP. Enter counter-trend targeting VWAP. Stop: 2× ATR from VWAP.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 14,
        "module_name": "pead_intraday_drift",
        "display_name": "Post-Earnings Announcement Drift (Intraday)",
        "tagline": "Ride the intraday continuation after strong earnings gap",
        "category": "Earnings",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 2.2,
        "win_rate_pub": 0.58,
        "max_dd_pub": -0.14,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=3847865",
        "paper_citation": "SSRN 3847865",
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Stocks with large positive earnings surprises tend to drift upward intraday. Buy the dip after the open on high-PEAD-score stocks.",
        "mechanics_md": "Filter: EPS surprise > 10%, gap > 3%. Entry: buy first pullback after 9:45 AM. Stop: below pre-market low. Target: close.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 15,
        "module_name": "gex_pin_reversion",
        "display_name": "GEX Pin Reversion",
        "tagline": "Exploit gamma exposure pinning near large OI strikes",
        "category": "Options Flow",
        "asset_class": "options",
        "time_horizon": "intraday",
        "difficulty": "advanced",
        "risk_profile": "standard",
        "published_sharpe": 1.7,
        "win_rate_pub": 0.60,
        "max_dd_pub": -0.10,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": "SpotGamma Research",
        "suggested_bot": "options_income",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Market makers hedge gamma exposure, causing price to pin near high-OI strikes expiration day. Fade moves away from the pin strike.",
        "mechanics_md": "Identify highest OI put/call strike within 2% of current price. On opex Friday, fade moves > 1% from pin strike targeting return to pin. Stop: > 2% from strike.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 16,
        "module_name": "fomc_drift",
        "display_name": "FOMC Pre-Announcement Drift",
        "tagline": "Markets drift upward in the 24 hours before FOMC announcements",
        "category": "Macro",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 1.3,
        "win_rate_pub": 0.65,
        "max_dd_pub": -0.06,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=2024814",
        "paper_citation": "Lucca & Moench (2015)",
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Buy SPY the day before an FOMC decision and exit at the 2 PM announcement. Historical edge is robust across decades.",
        "mechanics_md": "Entry: buy SPY at close on FOMC day-minus-1. Exit: close position at 1:55 PM on FOMC announcement day. No sizing adjustment needed.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 17,
        "module_name": "rsi_mean_reversion_daily",
        "display_name": "RSI(2) Mean Reversion",
        "tagline": "Buy extreme RSI(2) oversold readings in uptrending stocks",
        "category": "Mean Reversion",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 1.4,
        "win_rate_pub": 0.68,
        "max_dd_pub": -0.11,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": "Connors & Alvarez (2009)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Larry Connors' RSI(2) strategy: buy S&P 500 stocks when RSI(2) drops below 10 while price is above 200-day MA.",
        "mechanics_md": "Filter: price > 200-day MA. Entry: RSI(2) < 10 on daily close. Exit: RSI(2) > 70. Position size: equal weight. Works best on large-cap indices.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 18,
        "module_name": "cross_sectional_momentum",
        "display_name": "Cross-Sectional Momentum",
        "tagline": "Long top decile, short bottom decile of 12-1 month returns",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "position",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.0,
        "win_rate_pub": None,
        "max_dd_pub": -0.40,
        "decay_risk": "high",
        "source_url": "https://ssrn.com/abstract=299107",
        "paper_citation": "Jegadeesh & Titman (1993)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "The classic momentum factor: buy past 12-month winners (skip last month), short past losers. Monthly rebalance.",
        "mechanics_md": "Rank stocks by 12-1 month return. Long top decile, short bottom decile. Rebalance monthly. Use only liquid large-cap universe to minimize turnover costs.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 19,
        "module_name": "pairs_trading_cointegration",
        "display_name": "Pairs Trading (Cointegration)",
        "tagline": "Trade the spread between two cointegrated stocks",
        "category": "Mean Reversion",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "advanced",
        "risk_profile": "conservative",
        "published_sharpe": 1.2,
        "win_rate_pub": 0.60,
        "max_dd_pub": -0.12,
        "decay_risk": "high",
        "source_url": None,
        "paper_citation": "Gatev et al. (2006)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Find two stocks with a stable long-run relationship. When the spread widens beyond 2 standard deviations, bet on reversion.",
        "mechanics_md": "Step 1: Test for cointegration (Engle-Granger). Step 2: Estimate hedge ratio. Step 3: Enter long/short when z-score > 2. Exit when z-score < 0.5. Stop: z-score > 3.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 20,
        "module_name": "crypto_breakout_swing",
        "display_name": "Crypto Breakout Swing",
        "tagline": "Buy BTC/ETH breakouts from multi-week consolidation ranges",
        "category": "Momentum",
        "asset_class": "crypto",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "aggressive",
        "published_sharpe": 1.6,
        "win_rate_pub": 0.48,
        "max_dd_pub": -0.25,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "crypto_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Identify multi-week consolidation ranges in BTC or ETH. Enter on a weekly close above the range high.",
        "mechanics_md": "Define range: price within 10% band for ≥ 3 weeks. Entry: weekly close > range high. Stop: weekly close < range midpoint. Target: 2× range height above breakout.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 21,
        "module_name": "crypto_momentum_daily",
        "display_name": "Crypto Daily Momentum",
        "tagline": "Ride strong daily momentum in top-10 crypto assets",
        "category": "Momentum",
        "asset_class": "crypto",
        "time_horizon": "intraday",
        "difficulty": "intermediate",
        "risk_profile": "aggressive",
        "published_sharpe": 1.5,
        "win_rate_pub": 0.50,
        "max_dd_pub": -0.22,
        "decay_risk": "high",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "crypto_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Trade momentum on top-10 crypto by market cap. Enter on 4-hour trend confirmation, exit same session.",
        "mechanics_md": "Entry: 4-hour close above 20-period EMA with RSI(14) 55–75. Stop: below 20-period EMA. Target: 1.5× ATR. Close by session end.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 22,
        "module_name": "volatility_risk_premium",
        "display_name": "Volatility Risk Premium",
        "tagline": "Systematically sell S&P 500 options to harvest the vol risk premium",
        "category": "Options Income",
        "asset_class": "options",
        "time_horizon": "swing",
        "difficulty": "advanced",
        "risk_profile": "standard",
        "published_sharpe": 1.35,
        "win_rate_pub": 0.78,
        "max_dd_pub": -0.28,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=189840",
        "paper_citation": "Bakshi & Kapadia (2003)",
        "suggested_bot": "options_income",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Implied volatility consistently overestimates realized volatility. Systematically sell SPX straddles or strangles to harvest this premium.",
        "mechanics_md": "Entry: sell 30-DTE SPX strangle (10-delta each side) when VIX > 16. Target: 25% of credit. Stop: 200% of credit. Roll when 21 DTE remains.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 23,
        "module_name": "first_half_hour_predicts_last",
        "display_name": "First Half-Hour Predicts Last",
        "tagline": "The opening 30-min return predicts the final 30-min direction",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "beginner",
        "risk_profile": "standard",
        "published_sharpe": 1.25,
        "win_rate_pub": 0.55,
        "max_dd_pub": -0.08,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Statistical edge: the direction of the first 30 minutes predicts the direction of the final 30 minutes at above-chance rates.",
        "mechanics_md": "At 10:00 AM, determine first 30-min direction. Enter SPY in same direction at 3:00 PM. Exit at 3:50 PM. Filter: only trade when first 30-min move > 0.3%.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 24,
        "module_name": "low_volatility_factor",
        "display_name": "Low Volatility Factor",
        "tagline": "Low-vol stocks beat high-vol stocks on risk-adjusted basis",
        "category": "Factor Investing",
        "asset_class": "stocks",
        "time_horizon": "long_term",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 0.85,
        "win_rate_pub": None,
        "max_dd_pub": -0.22,
        "decay_risk": "low",
        "source_url": "https://ssrn.com/abstract=980865",
        "paper_citation": "Blitz & van Vliet (2007)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "The low-volatility anomaly: stocks with below-average 12-month realized volatility deliver superior risk-adjusted returns.",
        "mechanics_md": "Rank S&P 500 by 12-month realized volatility. Buy lowest-volatility quintile. Rebalance quarterly. Equal weight within quintile.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 25,
        "module_name": "quality_factor",
        "display_name": "Quality Factor (Profitability)",
        "tagline": "High-ROE, low-leverage stocks generate alpha long-term",
        "category": "Factor Investing",
        "asset_class": "stocks",
        "time_horizon": "long_term",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 0.9,
        "win_rate_pub": None,
        "max_dd_pub": -0.25,
        "decay_risk": "low",
        "source_url": "https://ssrn.com/abstract=2090360",
        "paper_citation": "Novy-Marx (2013)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Gross profitability predicts future returns. High gross-profit-to-assets stocks outperform, particularly in combination with value.",
        "mechanics_md": "Rank stocks by gross profit / total assets. Buy top 30%. Rebalance annually. Market-cap weight or equal weight.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 26,
        "module_name": "carry_trade_fx",
        "display_name": "FX Carry Trade",
        "tagline": "Borrow low-yield currencies, invest in high-yield currencies",
        "category": "Carry",
        "asset_class": "multi",
        "time_horizon": "position",
        "difficulty": "advanced",
        "risk_profile": "standard",
        "published_sharpe": 0.75,
        "win_rate_pub": None,
        "max_dd_pub": -0.35,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": "Brunnermeier et al. (2008)",
        "suggested_bot": "stock_lt",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Classic currency carry: long high-interest-rate currencies (AUD, NZD, BRL), short low-rate currencies (JPY, CHF). Tail risk in crisis.",
        "mechanics_md": "Rank G10 currencies by 3-month interest rate differential. Long top 3, short bottom 3. Rebalance monthly. Hard stop: 5% portfolio drawdown.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 27,
        "module_name": "statistical_arbitrage_etf",
        "display_name": "Statistical Arbitrage (ETF)",
        "tagline": "Exploit temporary mispricings between ETF and its NAV",
        "category": "Arbitrage",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "advanced",
        "risk_profile": "conservative",
        "published_sharpe": 1.1,
        "win_rate_pub": 0.65,
        "max_dd_pub": -0.05,
        "decay_risk": "high",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_day",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Trade discrepancies between ETF price and real-time estimated NAV. Arbitrage opportunities are typically small and short-lived.",
        "mechanics_md": "Calculate intraday iNAV using top holdings prices. Enter when ETF premium/discount > 0.15%. Exit when spread closes. Position size limited to 1% account.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 28,
        "module_name": "overnight_drift_spy",
        "display_name": "Overnight Drift (SPY)",
        "tagline": "Most of the S&P 500's gains occur overnight, not during market hours",
        "category": "Macro",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 0.95,
        "win_rate_pub": 0.60,
        "max_dd_pub": -0.18,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=2633833",
        "paper_citation": "Lachance (2015)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Buy SPY at close, sell at next day open. Captures the overnight risk premium that has historically exceeded daytime returns.",
        "mechanics_md": "Entry: buy SPY at 3:59 PM close. Exit: sell at 9:31 AM open next day. Filter: skip if VIX > 30 (elevated tail risk). No leverage.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 29,
        "module_name": "sector_rotation_monthly",
        "display_name": "Sector Rotation (Monthly)",
        "tagline": "Rotate into the top 3 S&P 500 sectors by 3-month momentum each month",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "position",
        "difficulty": "beginner",
        "risk_profile": "standard",
        "published_sharpe": 1.05,
        "win_rate_pub": None,
        "max_dd_pub": -0.28,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Rank the 11 GICS sectors by 3-month total return. Hold the top 3 equal-weight for one month, then rebalance.",
        "mechanics_md": "Monthly: rank sector ETFs (XLK, XLV, XLF, etc.) by 3-month return. Buy top 3 equal weight. Sell any that drop out of top 3. Rebalance first trading day.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 30,
        "module_name": "iron_condor_spy",
        "display_name": "Iron Condor (SPY)",
        "tagline": "Sell weekly SPY iron condors in low-volatility, range-bound regimes",
        "category": "Options Income",
        "asset_class": "options",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "conservative",
        "published_sharpe": None,
        "win_rate_pub": 0.70,
        "max_dd_pub": -0.15,
        "decay_risk": "low",
        "source_url": None,
        "paper_citation": "Practitioner",
        "suggested_bot": "options_income",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Sell a call spread and put spread on SPY for net credit. Profit if SPY stays within the wings at expiration.",
        "mechanics_md": "Entry: sell 7-10 DTE iron condor, short strikes at 16-delta. Collect ≥ $0.50 credit. Target: 50% of max profit. Stop: 200% of credit. Only trade when VIX < 25.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 31,
        "module_name": "buyback_yield_screen",
        "display_name": "Share Buyback Yield Screen",
        "tagline": "Buy stocks with highest buyback yield and rising EPS",
        "category": "Factor Investing",
        "asset_class": "stocks",
        "time_horizon": "long_term",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 0.95,
        "win_rate_pub": None,
        "max_dd_pub": -0.23,
        "decay_risk": "low",
        "source_url": "https://ssrn.com/abstract=2664176",
        "paper_citation": "Jiang & Lie (2016)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Stocks with aggressive buyback programs outperform. Screen for top-quartile buyback yield with positive EPS momentum.",
        "mechanics_md": "Screen: buyback yield (shares repurchased / market cap) > 3% TTM, EPS growth > 0 YoY, price > 200-day MA. Rebalance quarterly.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 32,
        "module_name": "crypto_dca_momentum",
        "display_name": "Crypto DCA with Momentum Filter",
        "tagline": "Dollar-cost average into BTC only when monthly momentum is positive",
        "category": "Momentum",
        "asset_class": "crypto",
        "time_horizon": "long_term",
        "difficulty": "beginner",
        "risk_profile": "conservative",
        "published_sharpe": 1.8,
        "win_rate_pub": None,
        "max_dd_pub": -0.45,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "crypto_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": True,
        "popularity_score": 0.0,
        "description_md": "Standard BTC DCA with a simple filter: skip the monthly buy if BTC is below its 12-month moving average. Reduces drawdown significantly.",
        "mechanics_md": "Monthly: if BTC price > 12-month SMA, invest fixed amount. If below, hold cash and resume next month when filter clears. No leverage.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 33,
        "module_name": "earnings_implied_move_fade",
        "display_name": "Earnings Implied Move Fade",
        "tagline": "Sell straddles before earnings when implied move > historical average",
        "category": "Earnings",
        "asset_class": "options",
        "time_horizon": "swing",
        "difficulty": "advanced",
        "risk_profile": "aggressive",
        "published_sharpe": None,
        "win_rate_pub": 0.65,
        "max_dd_pub": -0.30,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=2874168",
        "paper_citation": "Goyal & Saretto (2009)",
        "suggested_bot": "options_income",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Implied moves before earnings consistently overshoot actual moves. Sell the at-money straddle 1 day before earnings when IV rank > 50.",
        "mechanics_md": "Filter: IV rank > 50, implied move > 5-quarter avg actual move by > 20%. Sell ATM straddle 1 DTE to earnings. Exit day after earnings open.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 34,
        "module_name": "high_short_interest_squeeze",
        "display_name": "Short Squeeze Setup",
        "tagline": "Identify high short-interest stocks with catalysts for a squeeze",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "advanced",
        "risk_profile": "aggressive",
        "published_sharpe": None,
        "win_rate_pub": 0.40,
        "max_dd_pub": -0.25,
        "decay_risk": "high",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_swing",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "High short interest + positive catalyst + price breakout can ignite short covering. High risk, high reward.",
        "mechanics_md": "Filter: short interest > 20% of float, days-to-cover > 5, stock shows breakout above 20-day high on 3× average volume. Stop: below breakout day low.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 35,
        "module_name": "trend_following_futures",
        "display_name": "Trend Following (Futures)",
        "tagline": "Classic CTA trend following across diversified futures markets",
        "category": "Momentum",
        "asset_class": "multi",
        "time_horizon": "position",
        "difficulty": "advanced",
        "risk_profile": "standard",
        "published_sharpe": 0.8,
        "win_rate_pub": 0.40,
        "max_dd_pub": -0.25,
        "decay_risk": "low",
        "source_url": "https://ssrn.com/abstract=2553889",
        "paper_citation": "Hurst et al. (2017)",
        "suggested_bot": "stock_lt",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Time-series momentum across equity index, bond, FX, and commodity futures. Win rate is below 50% but average winner far exceeds average loser.",
        "mechanics_md": "For each market: if 12-month return > 0, go long 1 unit (volatility-scaled). If < 0, go short 1 unit. Monthly rebalance. Risk parity position sizing.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 36,
        "module_name": "opening_auction_imbalance",
        "display_name": "Opening Auction Imbalance",
        "tagline": "Trade in the direction of large pre-open order imbalances",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "advanced",
        "risk_profile": "standard",
        "published_sharpe": 2.0,
        "win_rate_pub": 0.58,
        "max_dd_pub": -0.10,
        "decay_risk": "high",
        "source_url": "https://ssrn.com/abstract=3498513",
        "paper_citation": "SSRN 3498513",
        "suggested_bot": "stock_day",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Stocks with large buy-side auction imbalances tend to drift up in the first hour. Use Nasdaq/NYSE imbalance data at 9:20 AM.",
        "mechanics_md": "At 9:25 AM: identify stocks with imbalance ratio > 3:1 (buy side) and imbalance size > $500K. Enter long at open. Exit by 10:30 AM or at 1% target.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 37,
        "module_name": "value_momentum_combo",
        "display_name": "Value + Momentum Combo",
        "tagline": "Buy cheap stocks that have recently started going up",
        "category": "Factor Investing",
        "asset_class": "stocks",
        "time_horizon": "position",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.15,
        "win_rate_pub": None,
        "max_dd_pub": -0.30,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=2404912",
        "paper_citation": "Asness et al. (2015)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Combining value (low P/B or P/E) and momentum (positive 12-1 month return) produces superior risk-adjusted returns vs either factor alone.",
        "mechanics_md": "Rank stocks by composite score: 50% value rank (low P/E) + 50% momentum rank (12-1 month return). Buy top quintile, sell bottom quintile. Rebalance quarterly.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 38,
        "module_name": "insider_buying_screen",
        "display_name": "Insider Buying Screen",
        "tagline": "Follow Form 4 cluster buys by C-suite insiders",
        "category": "Event-Driven",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.3,
        "win_rate_pub": 0.55,
        "max_dd_pub": -0.14,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=1089718",
        "paper_citation": "Cohen et al. (2012)",
        "suggested_bot": "stock_swing",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Cluster insider buys (2+ insiders buying within 30 days) signal conviction. Enter on the second insider buy Form 4 filing.",
        "mechanics_md": "Screen: 2+ unique insiders buying open-market shares within 30 days, each buying > $50K. Enter next morning open. Hold 3 months or until stop (10% from entry).",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 39,
        "module_name": "52_week_high_breakout",
        "display_name": "52-Week High Breakout",
        "tagline": "Stocks at 52-week highs continue to outperform short-term",
        "category": "Momentum",
        "asset_class": "stocks",
        "time_horizon": "swing",
        "difficulty": "beginner",
        "risk_profile": "standard",
        "published_sharpe": 1.4,
        "win_rate_pub": 0.55,
        "max_dd_pub": -0.12,
        "decay_risk": "medium",
        "source_url": "https://ssrn.com/abstract=1787366",
        "paper_citation": "George & Hwang (2004)",
        "suggested_bot": "stock_swing",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Stocks making new 52-week highs on above-average volume tend to continue higher over the next 1-3 months.",
        "mechanics_md": "Screen: new 52-week high on volume ≥ 1.5× 50-day average. Enter next open. Stop: 7% below entry. Hold 4-8 weeks or until stop.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 40,
        "module_name": "mean_reversion_overnight_gap",
        "display_name": "Overnight Gap Mean Reversion",
        "tagline": "Fade large overnight gaps that lack a fundamental catalyst",
        "category": "Mean Reversion",
        "asset_class": "stocks",
        "time_horizon": "intraday",
        "difficulty": "intermediate",
        "risk_profile": "standard",
        "published_sharpe": 1.6,
        "win_rate_pub": 0.62,
        "max_dd_pub": -0.09,
        "decay_risk": "medium",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "stock_day",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Large gaps without news tend to fill intraday. Fade the gap direction on the first pullback after open, targeting the prior close.",
        "mechanics_md": "Filter: gap > 1.5%, no earnings/news catalyst. Entry: after first 5-min candle, enter counter-gap direction on first pullback. Target: 50% gap fill. Stop: gap extreme.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 41,
        "module_name": "defi_yield_arbitrage",
        "display_name": "DeFi Yield Arbitrage",
        "tagline": "Capture yield differentials across DeFi lending protocols",
        "category": "Carry",
        "asset_class": "crypto",
        "time_horizon": "position",
        "difficulty": "advanced",
        "risk_profile": "aggressive",
        "published_sharpe": None,
        "win_rate_pub": None,
        "max_dd_pub": -0.50,
        "decay_risk": "high",
        "source_url": None,
        "paper_citation": None,
        "suggested_bot": "crypto_lt",
        "data_feed": "polygon_paid",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Deposit stablecoins into highest-yielding DeFi protocols. Monitor rate differentials and shift capital to maximize APY. Smart contract risk is significant.",
        "mechanics_md": "Monitor Aave, Compound, Morpho USDC lending rates. Deposit to highest-rate protocol. Rebalance when rate differential > 1% APY after gas costs. Cap: 20% of crypto allocation.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
    {
        "id": 42,
        "module_name": "risk_parity_daily",
        "display_name": "Risk Parity",
        "tagline": "Equal risk contribution from equities, bonds, gold, and commodities",
        "category": "Factor Investing",
        "asset_class": "multi",
        "time_horizon": "long_term",
        "difficulty": "intermediate",
        "risk_profile": "conservative",
        "published_sharpe": 0.9,
        "win_rate_pub": None,
        "max_dd_pub": -0.20,
        "decay_risk": "low",
        "source_url": "https://ssrn.com/abstract=2488552",
        "paper_citation": "Asness et al. (2012)",
        "suggested_bot": "stock_lt",
        "data_feed": "free_alpaca",
        "is_top_pick": False,
        "popularity_score": 0.0,
        "description_md": "Bridgewater-style risk parity: size each asset class so it contributes equal volatility to the portfolio. Leverage bonds to match equity vol.",
        "mechanics_md": "Assets: SPY (equities), TLT (bonds), GLD (gold), DJP (commodities). Size each to 10% annualized vol contribution. Rebalance monthly. Use modest leverage on bonds.",
        "when_works_md": None,
        "when_fails_md": None,
        "required_inputs": None,
    },
]


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.get("")
def get_strategy_library(
    category: Optional[str] = Query(None, description="Filter by category (e.g. Momentum)"),
    asset_class: Optional[str] = Query(None, description="Filter by asset class (stocks, crypto, options, multi)"),
    time_horizon: Optional[str] = Query(None, description="Filter by time horizon (intraday, swing, position, long_term)"),
    difficulty: Optional[str] = Query(None, description="Filter by difficulty (beginner, intermediate, advanced)"),
    search: Optional[str] = Query(None, description="Text search across display_name, tagline, and category"),
    suggested_bot: Optional[str] = Query(None, description="Filter by suggested bot profile name"),
    sort: str = Query("sharpe", description="Sort order: sharpe | alphabetical | top_pick"),
    is_top_pick: Optional[bool] = Query(None, description="Filter to top picks only"),
    current_user: User = Depends(get_current_user),
) -> Dict[str, Any]:
    """Return the full strategy catalog with optional filtering and sorting."""

    results = list(CATALOG)

    # ── Filters ──────────────────────────────────────────────────────────────
    if category is not None:
        results = [s for s in results if s.get("category", "").lower() == category.lower()]

    if asset_class is not None:
        results = [s for s in results if s.get("asset_class", "").lower() == asset_class.lower()]

    if time_horizon is not None:
        results = [s for s in results if s.get("time_horizon", "").lower() == time_horizon.lower()]

    if difficulty is not None:
        results = [s for s in results if s.get("difficulty", "").lower() == difficulty.lower()]

    if suggested_bot is not None:
        results = [s for s in results if s.get("suggested_bot", "").lower() == suggested_bot.lower()]

    if is_top_pick is not None:
        results = [s for s in results if s.get("is_top_pick") == is_top_pick]

    if search:
        q = search.lower()
        results = [
            s for s in results
            if q in (s.get("display_name") or "").lower()
            or q in (s.get("tagline") or "").lower()
            or q in (s.get("category") or "").lower()
            or q in (s.get("description_md") or "").lower()
        ]

    # ── Sort ─────────────────────────────────────────────────────────────────
    if sort == "alphabetical":
        results.sort(key=lambda s: (s.get("display_name") or "").lower())
    elif sort == "top_pick":
        results.sort(
            key=lambda s: (
                not s.get("is_top_pick", False),        # True (top picks) first
                -(s.get("published_sharpe") or 0.0),   # then by sharpe desc
            )
        )
    else:  # default: sharpe
        results.sort(key=lambda s: -(s.get("published_sharpe") or 0.0))

    # ── Category counts (on the un-filtered full catalog) ────────────────────
    category_counts: Dict[str, int] = {}
    for s in CATALOG:
        cat = s.get("category") or "Uncategorized"
        category_counts[cat] = category_counts.get(cat, 0) + 1

    return {
        "strategies": results,
        "total": len(results),
        "categories": category_counts,
    }
