"""
BMG Capital — Market Challenge Puzzle Library
Hardcoded puzzle bank used to seed MarketChallenge rows.
Each entry is picked by: day_of_year % len(CHALLENGE_LIBRARY)
Minimum 35 entries, >= 5 per challenge_type.
"""
from __future__ import annotations

CHALLENGE_LIBRARY: list[dict] = [
    # ── chart_pattern (Technical) ────────────────────────────────────────────
    {
        "challenge_type": "chart_pattern",
        "category": "Technical",
        "difficulty": "intermediate",
        "question": "A stock makes a higher high, then a lower high, then breaks below the neckline. What pattern is this?",
        "options": ["Head and Shoulders", "Double Bottom", "Bull Flag", "Ascending Triangle"],
        "correct_idx": 0,
        "explanation": "Head and Shoulders is a classic topping pattern: left shoulder, head (higher high), right shoulder (lower high), then a decisive break below the neckline confirms the reversal.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "chart_pattern",
        "category": "Technical",
        "difficulty": "beginner",
        "question": "Price consolidates in a tight range after a strong up-move. Volume drops. What comes next in a bull flag?",
        "options": ["Breakout higher", "Reversal lower", "Extended sideways drift", "Volume spike then drop"],
        "correct_idx": 0,
        "explanation": "A bull flag is a continuation pattern. The 'flag' is the low-volume consolidation; the breakout to the upside on expanding volume is the expected resolution.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "chart_pattern",
        "category": "Technical",
        "difficulty": "intermediate",
        "question": "A stock makes two roughly equal lows separated by a moderate bounce. What is this pattern called?",
        "options": ["Double Bottom", "Head and Shoulders", "Bear Flag", "Descending Triangle"],
        "correct_idx": 0,
        "explanation": "A Double Bottom (W-shape) signals a potential trend reversal from bearish to bullish. Confirmation comes when price breaks above the middle peak (neckline).",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "chart_pattern",
        "category": "Technical",
        "difficulty": "advanced",
        "question": "A descending triangle has a flat support line and a falling upper trendline. In a downtrend, what does a breakdown below support typically signal?",
        "options": ["Bearish continuation lower", "Bullish reversal", "Indecision / sideways", "Gap fill then reversal"],
        "correct_idx": 0,
        "explanation": "A descending triangle in a downtrend is a bearish continuation. Sellers compress price at a flat support until supply overwhelms demand and price breaks lower.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "chart_pattern",
        "category": "Technical",
        "difficulty": "intermediate",
        "question": "A cup and handle pattern forms. Volume is highest on the left lip, low during the cup, and picks up on the handle breakout. What is the expected move direction?",
        "options": ["Upside breakout", "Downside breakdown", "Flat consolidation", "Gap down open"],
        "correct_idx": 0,
        "explanation": "Cup and Handle is a bullish continuation. William O'Neil popularized it: the cup forms a rounded bottom, the handle is a brief pullback, then price breaks above the rim on volume.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "chart_pattern",
        "category": "Technical",
        "difficulty": "beginner",
        "question": "Which pattern features two peaks at roughly the same level, separated by a trough, signaling potential bearish reversal?",
        "options": ["Double Top", "Double Bottom", "Ascending Triangle", "Bull Pennant"],
        "correct_idx": 0,
        "explanation": "A Double Top (M-shape) is a bearish reversal pattern. After two failed attempts to push above resistance, sellers typically take control when price breaks below the neckline.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },

    # ── predict_close (Macro) ────────────────────────────────────────────────
    {
        "challenge_type": "predict_close",
        "category": "Macro",
        "difficulty": "intermediate",
        "question": "SPY opens -0.8% on higher-than-expected CPI. The Fed speaks at 2pm. Based on historical patterns, what's the most common outcome by close?",
        "options": ["Reversal to flat or green", "Continued sell-off", "Unchanged open losses", "Circuit breaker triggered"],
        "correct_idx": 0,
        "explanation": "Fed-day sell-offs often partially reverse as traders front-run the statement. Not guaranteed, but historically the most common pattern — especially when the initial reaction seems overdone.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "predict_close",
        "category": "Macro",
        "difficulty": "advanced",
        "question": "10-year Treasury yield gaps up 15 bps after a hot PPI print. Growth stocks open down 2%. Historically, where does the Nasdaq close relative to its open on such days?",
        "options": ["Usually recovers > 50% of losses by close", "Accelerates lower throughout the day", "Flat — pre-market moves fade completely", "Closes exactly at session low"],
        "correct_idx": 0,
        "explanation": "Historical data shows that large Nasdaq gaps down on rate-shock days frequently see intraday mean reversion as buyers step in after the initial panic selling exhausts itself.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "predict_close",
        "category": "Macro",
        "difficulty": "beginner",
        "question": "The jobs report comes in much stronger than expected. Which asset typically falls as a direct result?",
        "options": ["Long-duration Treasury bonds", "Gold", "Crude oil", "Small-cap value stocks"],
        "correct_idx": 0,
        "explanation": "Strong jobs data raises expectations for Fed rate hikes (or fewer cuts). Higher rates make future bond cash flows less valuable, so long-duration Treasuries fall in price (yields rise).",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "predict_close",
        "category": "Macro",
        "difficulty": "intermediate",
        "question": "VIX spikes above 30 during a geopolitical shock. SPY opens -2.5%. Historically, what is the most common 5-day outcome for SPY?",
        "options": ["Partial recovery — mean reversion inward", "Continued slide to new lows", "Immediate V-shaped recovery same day", "Flat — holds the shock level for weeks"],
        "correct_idx": 0,
        "explanation": "Geopolitical shock spikes in VIX above 30 historically mark fear extremes. The 5-day window typically shows partial recovery as panic sellers exhaust and value buyers emerge.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "predict_close",
        "category": "Macro",
        "difficulty": "advanced",
        "question": "Fed delivers a surprise 50bps hike (vs 25bps expected). In the first 30 minutes, markets rally. What does history suggest happens by end of day?",
        "options": ["Selloff reversal — initial relief rally fades", "Rally continues — markets cheer decisiveness", "Unchanged — opens and closes at same level", "Circuit breakers halt trading"],
        "correct_idx": 0,
        "explanation": "The 'buy the news, sell the fact' pattern frequently plays out after shock rate hikes. The initial relief rally ('Fed has control') fades as traders price in economic slowdown risk.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },

    # ── earnings_beat ────────────────────────────────────────────────────────
    {
        "challenge_type": "earnings_beat",
        "category": "Fundamental",
        "difficulty": "beginner",
        "question": "It's earnings season. Which of these is a REAL earnings beat?",
        "options": [
            "NVDA: EPS $5.16 vs $4.64 est, rev $22.1B vs $20.4B est",
            "AAPL: EPS $1.53 vs $1.60 est, rev $94.9B vs $96.1B est",
            "META: EPS $3.21 vs $3.85 est, rev $34.1B vs $38.3B est",
            "AMZN: EPS $0.94 vs $1.02 est, rev $143B vs $148B est",
        ],
        "correct_idx": 0,
        "explanation": "NVDA beat on both EPS ($5.16 vs $4.64 est) and revenue ($22.1B vs $20.4B est). The others all missed — actual results came in below analyst estimates.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "earnings_beat",
        "category": "Fundamental",
        "difficulty": "intermediate",
        "question": "A company beats EPS by 12% but guides revenue 5% below consensus for next quarter. What typically happens to the stock?",
        "options": ["Sells off — guidance matters more than backward-looking EPS", "Rallies on the EPS beat", "No movement — guidance and EPS cancel out", "Halted pending clarification"],
        "correct_idx": 0,
        "explanation": "Markets are forward-looking. A weak forward guidance typically overshadows a backward-looking EPS beat. The phrase 'beat and lower' often leads to a sell-off.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "earnings_beat",
        "category": "Fundamental",
        "difficulty": "intermediate",
        "question": "What does it mean when analysts say a company reported 'whisper number' earnings?",
        "options": [
            "Beat the unofficial buy-side expectation above published consensus",
            "Missed the official consensus estimate",
            "Reported before the market open",
            "Filed an amended 10-Q after the report",
        ],
        "correct_idx": 0,
        "explanation": "The 'whisper number' is the unofficial, often higher expectation held by sophisticated buy-side traders. Beating consensus but missing the whisper can still send a stock lower.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "earnings_beat",
        "category": "Fundamental",
        "difficulty": "advanced",
        "question": "Company reports EPS of $2.10 vs $1.95 estimate (8% beat). Stock drops 7% after hours. What's the most likely cause?",
        "options": [
            "Revenue miss or weak guidance despite EPS beat",
            "EPS was calculated incorrectly by the company",
            "The exchange suspended trading",
            "A competitor reported strong earnings simultaneously",
        ],
        "correct_idx": 0,
        "explanation": "An EPS beat driven by cost cuts or buybacks (not revenue growth) with weak forward guidance is a classic 'quality miss.' Markets punish low-quality beats.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "earnings_beat",
        "category": "Fundamental",
        "difficulty": "beginner",
        "question": "What is 'earnings per share' (EPS)?",
        "options": [
            "Net income divided by shares outstanding",
            "Total revenue divided by share price",
            "Operating income minus taxes",
            "Cash flow from operations per quarter",
        ],
        "correct_idx": 0,
        "explanation": "EPS = Net Income / Diluted Shares Outstanding. It standardizes profitability on a per-share basis, making comparison across companies and quarters easier.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },

    # ── 10k_translation ──────────────────────────────────────────────────────
    {
        "challenge_type": "10k_translation",
        "category": "Fundamental",
        "difficulty": "intermediate",
        "question": '"We may not be able to generate positive cash flow from operations in the near term." What does this 10-K phrase mean?',
        "options": [
            "We might keep losing money operationally",
            "We have plenty of cash but choose not to invest it",
            "Operations are profitable but capex is high",
            "Cash flow is positive but reported net loss due to depreciation",
        ],
        "correct_idx": 0,
        "explanation": "This is boilerplate risk-factor language for pre-profitable or early-stage companies signaling they may continue burning cash from operations — a meaningful red flag for near-term investors.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "10k_translation",
        "category": "Fundamental",
        "difficulty": "intermediate",
        "question": '"Our results of operations may fluctuate significantly from period to period." What risk is the company flagging?',
        "options": [
            "Earnings will be lumpy and unpredictable quarter to quarter",
            "The company is planning a stock split",
            "Revenue is seasonal but always grows annually",
            "The company is about to merge with a competitor",
        ],
        "correct_idx": 0,
        "explanation": "This is a standard 10-K disclosure warning investors that consistent quarter-over-quarter comparisons may be misleading. Often seen in project-based, contract, or cyclical businesses.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "10k_translation",
        "category": "Fundamental",
        "difficulty": "advanced",
        "question": '"We have identified a material weakness in our internal controls over financial reporting." What should investors do first?',
        "options": [
            "Treat reported financials with skepticism until remediated",
            "Immediately buy — the stock will rebound once fixed",
            "Ignore it — all companies disclose this",
            "Assume fraud and sell immediately",
        ],
        "correct_idx": 0,
        "explanation": "A material weakness means the company cannot reliably ensure its financial statements are accurate. This is serious but not necessarily fraud — it warrants heightened due diligence until an auditor confirms remediation.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "10k_translation",
        "category": "Fundamental",
        "difficulty": "beginner",
        "question": '"Concentration risk: one customer represented 38% of our revenue in fiscal 2025." Why is this a risk?',
        "options": [
            "Losing that one customer would cut revenue by 38%",
            "The company has too many customers to manage effectively",
            "38% is below the legal threshold for diversification",
            "The customer has a better credit rating than the company",
        ],
        "correct_idx": 0,
        "explanation": "Customer concentration risk means the business is heavily dependent on a single relationship. If that customer churns, delays orders, or goes bankrupt, the revenue impact is immediate and severe.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "10k_translation",
        "category": "Fundamental",
        "difficulty": "advanced",
        "question": '"We use non-GAAP financial measures that exclude stock-based compensation." Why might analysts be cautious here?',
        "options": [
            "SBC is a real cost to shareholders even if non-cash",
            "Non-GAAP is always more accurate than GAAP",
            "The SEC requires exclusion of SBC from earnings",
            "Stock compensation only affects the balance sheet, not income",
        ],
        "correct_idx": 0,
        "explanation": "Stock-based compensation dilutes existing shareholders. When management excludes it from 'adjusted' earnings, they present a more flattering picture. Sophisticated investors add it back to assess true economic profitability.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },

    # ── strategy_fit ─────────────────────────────────────────────────────────
    {
        "challenge_type": "strategy_fit",
        "category": "Options",
        "difficulty": "advanced",
        "question": "Volatility just spiked, IV rank is 82nd percentile on SPY. The trend is sideways. Which strategy fits best?",
        "options": [
            "Iron Condor (sell premium on both sides)",
            "Long Straddle (buy IV)",
            "Bull Call Spread",
            "Covered Call only",
        ],
        "correct_idx": 0,
        "explanation": "When IV rank is high (above ~50th percentile) and the underlying is range-bound, selling premium via an Iron Condor profits from IV crush. Buying premium (Long Straddle) in high-IV conditions is expensive and usually unprofitable.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "strategy_fit",
        "category": "Options",
        "difficulty": "intermediate",
        "question": "You're bullish on AAPL but want to reduce the cost of a directional bet. The stock is at $200. Which strategy best fits?",
        "options": [
            "Bull Call Spread ($200/$215 calls)",
            "Long ATM Call only",
            "Short Put spread below support",
            "Iron Condor",
        ],
        "correct_idx": 0,
        "explanation": "A Bull Call Spread (buy lower strike, sell higher strike) reduces premium paid vs. a naked long call while still providing leveraged upside exposure. The short upper call caps gains but funds the trade.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "strategy_fit",
        "category": "Options",
        "difficulty": "advanced",
        "question": "You own 500 shares of MSFT and expect sideways drift for the next 30 days. Which strategy generates income without selling your position?",
        "options": [
            "Covered Call — sell OTM calls against your shares",
            "Buy Put options for protection",
            "Long Straddle",
            "Buy additional shares at market",
        ],
        "correct_idx": 0,
        "explanation": "A covered call generates premium income by selling the right for someone else to buy your shares at a higher price (strike). If MSFT stays flat or moves slightly up, you keep the premium and the shares.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "strategy_fit",
        "category": "Options",
        "difficulty": "intermediate",
        "question": "Earnings are in 3 days, IV rank is 15th percentile. You expect a big move but are unsure of direction. What fits?",
        "options": [
            "Long Straddle (buy both ATM call and put)",
            "Iron Condor (sell premium on both sides)",
            "Covered Call",
            "Short Put",
        ],
        "correct_idx": 0,
        "explanation": "When IV is low (cheap options) and you expect a large directional move without certainty on direction, a Long Straddle profits from a large move either way — paying relatively low premium at low IV.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "strategy_fit",
        "category": "Options",
        "difficulty": "beginner",
        "question": "You are bearish on a stock and want limited risk. Which strategy is most appropriate?",
        "options": [
            "Buy Put options",
            "Sell naked call options",
            "Buy the stock and hold",
            "Sell cash-secured puts",
        ],
        "correct_idx": 0,
        "explanation": "Buying put options gives you the right to sell at the strike price. Your max loss is limited to the premium paid, making it a defined-risk bearish strategy — unlike selling naked calls where losses are theoretically unlimited.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },

    # ── risk_check ───────────────────────────────────────────────────────────
    {
        "challenge_type": "risk_check",
        "category": "Risk",
        "difficulty": "beginner",
        "question": "You own 200 shares at $150. Your stop is $142. What is your maximum dollar risk?",
        "options": ["$1,600", "$28,400", "$800", "$3,000"],
        "correct_idx": 0,
        "explanation": "200 shares × ($150 − $142) = 200 × $8 = $1,600 max loss. This is the risk per trade — knowing this lets you size positions so no single trade destroys your account.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "risk_check",
        "category": "Risk",
        "difficulty": "intermediate",
        "question": "You have a $50,000 account and want to risk no more than 2% per trade. Your stop is $5 below entry. What is your max share size?",
        "options": ["200 shares", "100 shares", "500 shares", "50 shares"],
        "correct_idx": 0,
        "explanation": "2% of $50,000 = $1,000 max risk. $1,000 ÷ $5 stop = 200 shares. Position sizing based on account risk % prevents catastrophic drawdowns from any single trade.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "risk_check",
        "category": "Risk",
        "difficulty": "advanced",
        "question": "Your account is down 40% from its peak. What return do you need to break even?",
        "options": ["~67%", "40%", "60%", "50%"],
        "correct_idx": 0,
        "explanation": "Starting at $100K, a 40% loss leaves you at $60K. To return to $100K: $40K / $60K ≈ 66.7% gain required. Asymmetric math — this is why limiting drawdowns is more important than chasing gains.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "risk_check",
        "category": "Risk",
        "difficulty": "intermediate",
        "question": "A position has a potential gain of $1,500 and you risk $500. What is the risk/reward ratio?",
        "options": ["3:1 (favorable)", "1:3 (unfavorable)", "1:1 (breakeven)", "5:1 (exceptional)"],
        "correct_idx": 0,
        "explanation": "Risk/reward = Potential Gain / Risk = $1,500 / $500 = 3:1. A 3:1 ratio means you only need to be right 25% of the time to be profitable at breakeven — a solid setup.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "risk_check",
        "category": "Risk",
        "difficulty": "advanced",
        "question": "You have 10 open positions. Each is 10% of your portfolio. A 25% market crash hits. What is your approximate portfolio loss?",
        "options": ["~25% (fully correlated)", "~10% (only 1 position affected)", "~5% (diversification protects)", "~50% (leverage amplifies)"],
        "correct_idx": 0,
        "explanation": "In a sharp market crash, correlations spike toward 1. Ten 10%-positions all drop ~25% together = approximately 25% portfolio loss. Diversification reduces idiosyncratic risk but not systemic risk.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },

    # ── greek_check ──────────────────────────────────────────────────────────
    {
        "challenge_type": "greek_check",
        "category": "Options",
        "difficulty": "beginner",
        "question": "You hold a long call. Time passes and nothing else changes. What happens to its value?",
        "options": [
            "It decreases (theta decay)",
            "It increases",
            "It stays the same",
            "It depends only on delta",
        ],
        "correct_idx": 0,
        "explanation": "Theta (time decay) erodes option value every day. Long options are always 'long theta decay' — you are paying for time, and each day that passes with no movement costs you premium.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "greek_check",
        "category": "Options",
        "difficulty": "intermediate",
        "question": "A call option has a delta of 0.60. The underlying moves up $1. Approximately how much does the option price change?",
        "options": ["$0.60", "$1.00", "$0.40", "$0.06"],
        "correct_idx": 0,
        "explanation": "Delta measures the rate of change in option price per $1 move in the underlying. Delta 0.60 means the option gains approximately $0.60 for every $1 the stock rises (before gamma adjusts delta further).",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "greek_check",
        "category": "Options",
        "difficulty": "advanced",
        "question": "Vega is 0.15 and implied volatility rises by 2 percentage points. How much does the option price increase?",
        "options": ["$0.30", "$0.15", "$2.00", "$0.03"],
        "correct_idx": 0,
        "explanation": "Vega = change in option price per 1% change in IV. 0.15 × 2 = $0.30 increase. Long options benefit from rising IV (positive vega); short options are hurt by rising IV.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "greek_check",
        "category": "Options",
        "difficulty": "intermediate",
        "question": "Which Greek measures the rate of change of delta as the underlying moves?",
        "options": ["Gamma", "Theta", "Vega", "Rho"],
        "correct_idx": 0,
        "explanation": "Gamma measures how fast delta changes per $1 move in the underlying. High gamma (near ATM, short-dated options) means delta can shift rapidly — creating large swings in P&L for small moves.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "greek_check",
        "category": "Options",
        "difficulty": "advanced",
        "question": "You have a short strangle (sold OTM call + OTM put). Which Greek exposure creates the most risk if markets move violently?",
        "options": [
            "Short gamma — losses accelerate as underlying moves far",
            "Long vega — rising IV hurts position",
            "Positive theta — time decay works against you",
            "High rho — interest rate changes hurt short premium",
        ],
        "correct_idx": 0,
        "explanation": "A short strangle is short gamma. As the underlying makes large moves, gamma causes delta to move against you rapidly, accelerating losses. This is why short premium traders fear 'gap risk' and tail events.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 75,
    },
    {
        "challenge_type": "greek_check",
        "category": "Options",
        "difficulty": "beginner",
        "question": "An at-the-money (ATM) call option has approximately what delta?",
        "options": ["0.50", "1.00", "0.00", "0.25"],
        "correct_idx": 0,
        "explanation": "ATM options have delta ≈ 0.50 because there's roughly a 50% chance the option expires in the money. Deep in-the-money calls approach delta 1.0; far out-of-the-money calls approach 0.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },

    # ── Additional chart_pattern entries to reach >= 5 (already have 6) ──────
    # ── Extra entries for variety ─────────────────────────────────────────────
    {
        "challenge_type": "predict_close",
        "category": "Macro",
        "difficulty": "beginner",
        "question": "The Fed raises interest rates by 0.25%. Which sector typically underperforms in the immediate aftermath?",
        "options": [
            "Real estate (REITs) — rising rates increase borrowing costs",
            "Energy — oil prices are insensitive to rate changes",
            "Consumer staples — demand for necessities doesn't change",
            "Healthcare — regulated pricing unaffected by rates",
        ],
        "correct_idx": 0,
        "explanation": "REITs are rate-sensitive because they rely on debt financing and their dividend yields compete directly with risk-free Treasury yields. Higher rates = higher cap rates = lower REIT valuations.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
    {
        "challenge_type": "earnings_beat",
        "category": "Fundamental",
        "difficulty": "intermediate",
        "question": "A company beats EPS estimates for the 8th consecutive quarter but the stock is still at the same price from a year ago. What might explain this?",
        "options": [
            "The beats were already priced in (P/E multiple compression)",
            "EPS is not a valid metric for valuing stocks",
            "The company must have diluted shares heavily each quarter",
            "Retail investors only buy on misses, not beats",
        ],
        "correct_idx": 0,
        "explanation": "When consistently positive results are already 'priced in,' the stock's forward P/E ratio compresses even as EPS grows. The market may have been pricing in the future beats all along — requiring even bigger upside surprises to move higher.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "10k_translation",
        "category": "Fundamental",
        "difficulty": "intermediate",
        "question": '"Our intellectual property may not adequately protect us from competitors." What risk is this disclosing?',
        "options": [
            "Competitors could copy the product or technology legally or illegally",
            "The company owns no patents",
            "Management does not value innovation",
            "The company is planning to license its IP",
        ],
        "correct_idx": 0,
        "explanation": "IP risk language warns that patents may be invalid, narrow, hard to enforce, or about to expire. A moat-less business is one where competitors can erode pricing power by replicating core products.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "strategy_fit",
        "category": "Options",
        "difficulty": "intermediate",
        "question": "You want to own 100 shares of a stock at a cheaper price. You're comfortable buying at $95 (currently $100). Which strategy earns you income while waiting?",
        "options": [
            "Sell a cash-secured put at the $95 strike",
            "Buy a call at the $95 strike",
            "Buy the stock at market and set a stop at $95",
            "Sell a covered call at $95",
        ],
        "correct_idx": 0,
        "explanation": "Selling a cash-secured put at $95 obligates you to buy the stock at $95 if assigned — your intended entry anyway. You collect premium upfront. If the stock stays above $95, you keep the premium as income.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 50,
    },
    {
        "challenge_type": "risk_check",
        "category": "Risk",
        "difficulty": "beginner",
        "question": "Which of these is an example of diversification reducing portfolio risk?",
        "options": [
            "Owning stocks across tech, healthcare, energy, and financials",
            "Owning 10 different tech stocks",
            "Owning the same stock in 3 different brokerage accounts",
            "Doubling your position size to average down",
        ],
        "correct_idx": 0,
        "explanation": "True diversification means exposure to different sectors, geographies, or asset classes that have low correlations. Owning 10 tech stocks is concentration, not diversification — they tend to move together.",
        "share_emoji": "🟩🟥🟥🟥",
        "xp_value": 30,
    },
]
