"""state_current_regen.py — auto-regenerate the COVERAGE block in state/current.md.

Rationale (2026-09-12):
    TEST 2 established that a fresh sub-agent asked "Is GATX exposed to coal?"
    answered from prior knowledge without reading the coverage note. The
    S1-disclosure trigger in CLAUDE.md's mid-session prose did not fire.

    Session-start reads of state/current.md DO fire reliably. So we relocate
    coverage awareness into the file that gets read every session — but
    generate it from the directory instead of maintaining it by hand, so it
    cannot drift.

What this script does:
    - Scans `research/coverage/<sector>/*.md` under the vault
    - Identifies "covered names" by finding distinct filename prefixes that
      look like company slugs (before the first `-`)
    - Emits a COVERAGE block into state/current.md between
      `<!-- coverage-auto-start -->` and `<!-- coverage-auto-end -->` markers
    - Preserves everything else in state/current.md verbatim
    - Optional `--shipped <path>` flag rewrites the "Last session" line with
      today's date and the shipped-doc name

Filename heuristic (subject notes vs sector-level notes vs auxiliaries):
    <slug>-<topic>.md     -> subject note for name `<slug>`
    <slug>-<topic>-sources.md -> companion sources file for the same subject note (skipped in listing)
    peer-*.md, industry-*.md -> sector-level, not a specific covered name
    falsified.md          -> the audit ledger
    vault-intake-*.md     -> raw intake dumps

Usage:
    python3 scripts/local/state_current_regen.py
    python3 scripts/local/state_current_regen.py --shipped research/002-railcar-supply.md
    python3 scripts/local/state_current_regen.py --vault /path/to/vault
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

DEFAULT_VAULT = Path("~/Documents/BMG-Capital-Vault").expanduser()

COVERAGE_START = "<!-- coverage-auto-start"
COVERAGE_END = "<!-- coverage-auto-end -->"
METHOD_START = "<!-- method-auto-start"
METHOD_END = "<!-- method-auto-end -->"

# Stopword prefixes that are NOT company names.
NON_COMPANY_PREFIXES = {"peer", "industry", "vault", "falsified"}

# Verbatim instruction that MUST appear at the end of the coverage block.
COVERAGE_TRAILER = (
    "For any factual question about a covered name, read its subject notes in "
    "research/coverage/<sector>/ BEFORE answering. Do not answer from prior "
    "knowledge. If the note does not contain the figure, say so and go to the "
    "filing."
)

METHOD_TRAILER = (
    "Before drawing a rule from a piece of work, check whether the method "
    "layer already has it. If yes, cite the M-ID. If no, propose adding one "
    "at the end of the note. Every shipped research note contributes at "
    "least one method entry, or records that it taught nothing generalisable."
)


def enumerate_sectors(vault: Path) -> list[Path]:
    coverage = vault / "research" / "coverage"
    if not coverage.exists():
        return []
    return sorted([p for p in coverage.iterdir() if p.is_dir()])


def scan_sector(sector_dir: Path) -> tuple[dict[str, list[str]], list[str]]:
    """Return (covered_names -> list of subject note relpaths, sector-level notes)."""
    names: dict[str, list[str]] = defaultdict(list)
    sector_level: list[str] = []
    for f in sorted(sector_dir.iterdir()):
        if not f.is_file() or f.suffix != ".md":
            continue
        stem = f.stem
        if stem.endswith("-sources"):
            continue  # companion sources file — skip listing
        if stem == "falsified":
            sector_level.append(f.name)  # ledger — sector-level reference
            continue
        if stem.startswith("vault-intake-"):
            continue  # raw intake dumps — not a running reference
        # Split on first hyphen
        if "-" not in stem:
            sector_level.append(f.name)
            continue
        prefix = stem.split("-", 1)[0].lower()
        if prefix in NON_COMPANY_PREFIXES:
            sector_level.append(f.name)
            continue
        names[prefix].append(f.name)
    return dict(names), sector_level


def build_coverage_block(vault: Path) -> str:
    lines: list[str] = []
    lines.append("<!-- coverage-auto-start: generated by scripts/local/state_current_regen.py — do not edit by hand -->")
    lines.append("")
    lines.append("## Coverage")
    lines.append("")

    any_content = False
    for sector_dir in enumerate_sectors(vault):
        names, sector_notes = scan_sector(sector_dir)
        if not names and not sector_notes:
            continue
        any_content = True
        sector = sector_dir.name
        lines.append(f"### {sector}")
        lines.append("")
        for slug in sorted(names.keys()):
            display = slug.upper()  # heuristic: uppercase slug is ticker AND display name
            # Some slugs are the ticker; if in the future the display name and ticker differ,
            # add a per-slug map to a manifest file. For now, GATX == GATX.
            lines.append(f"- **{display}** (ticker: {display})")
            for note_name in sorted(names[slug]):
                lines.append(f"  - `research/coverage/{sector}/{note_name}`")
            lines.append("")
        if sector_notes:
            lines.append(f"#### {sector} — sector-level notes")
            lines.append("")
            for n in sorted(sector_notes):
                lines.append(f"- `research/coverage/{sector}/{n}`")
            lines.append("")

    if not any_content:
        lines.append("_(no coverage directories with content yet)_")
        lines.append("")

    lines.append(COVERAGE_TRAILER)
    lines.append("")
    lines.append(COVERAGE_END)
    return "\n".join(lines)


COVERAGE_BLOCK_RE = re.compile(
    rf"{re.escape(COVERAGE_START)}.*?{re.escape(COVERAGE_END)}",
    re.DOTALL,
)

METHOD_BLOCK_RE = re.compile(
    rf"{re.escape(METHOD_START)}.*?{re.escape(METHOD_END)}",
    re.DOTALL,
)


def upsert_coverage_block(state_text: str, new_block: str) -> str:
    if COVERAGE_BLOCK_RE.search(state_text):
        return COVERAGE_BLOCK_RE.sub(new_block, state_text)
    # Insert before the last section ("## Last session") if present, else append
    if "## Last session" in state_text:
        return state_text.replace("## Last session", new_block + "\n## Last session", 1)
    if not state_text.endswith("\n"):
        state_text += "\n"
    return state_text + "\n" + new_block + "\n"


def build_method_block(vault: Path) -> str:
    """Enumerate /reference/method/M##.md and emit a table."""
    method_dir = vault / "reference" / "method"
    lines: list[str] = []
    lines.append("<!-- method-auto-start: generated by scripts/local/state_current_regen.py — do not edit by hand -->")
    lines.append("")
    lines.append("## Method layer")
    lines.append("")
    if not method_dir.exists():
        lines.append("_(no /reference/method/ directory)_")
        lines.append("")
        lines.append(METHOD_TRAILER)
        lines.append("")
        lines.append(METHOD_END)
        return "\n".join(lines)

    entries: list[tuple[str, str]] = []  # (id, title)
    for f in sorted(method_dir.iterdir()):
        if not f.is_file() or f.suffix != ".md":
            continue
        if not re.match(r"^M\d+$", f.stem):
            continue  # skip 00-index and any non-M-numbered files
        text = f.read_text(encoding="utf-8")
        # Extract id + title from frontmatter
        m_id = re.search(r"^id:\s*(\S+)", text, re.MULTILINE)
        m_title = re.search(r"^title:\s*(.+)$", text, re.MULTILINE)
        if not m_id or not m_title:
            continue
        entries.append((m_id.group(1), m_title.group(1).strip()))

    if not entries:
        lines.append("_(/reference/method/ has no M##.md files yet)_")
    else:
        lines.append("| ID | Rule |")
        lines.append("|----|------|")
        for mid, title in entries:
            lines.append(f"| [{mid}](../reference/method/{mid}.md) | {title} |")
    lines.append("")
    lines.append(METHOD_TRAILER)
    lines.append("")
    lines.append(METHOD_END)
    return "\n".join(lines)


def upsert_method_block(state_text: str, new_block: str) -> str:
    if METHOD_BLOCK_RE.search(state_text):
        return METHOD_BLOCK_RE.sub(new_block, state_text)
    # Insert AFTER coverage block if present, so the two sit together
    if COVERAGE_END in state_text:
        return state_text.replace(
            COVERAGE_END,
            COVERAGE_END + "\n\n" + new_block,
            1,
        )
    # Otherwise insert before Last session
    if "## Last session" in state_text:
        return state_text.replace("## Last session", new_block + "\n## Last session", 1)
    if not state_text.endswith("\n"):
        state_text += "\n"
    return state_text + "\n" + new_block + "\n"


def rewrite_last_session(state_text: str, shipped_rel: str, today: str) -> str:
    """Update the 'Last session' block with today's date + shipped-doc line.

    We keep the existing 'Last session' content as prior history if it exists,
    but the top of the block gets a fresh line naming today's ship.

    Actually — the CLAUDE.md rule for state/current.md says the file has NO
    history / narrative, and last session is a single line. So we overwrite:
    date + one line naming the shipped doc.
    """
    new_body = f"**{today}** — shipped `{shipped_rel}` through vault_ship_gate.sh (provenance + falsified-audit clean)."
    # Replace everything from "## Last session" to end-of-file with the fresh line.
    if "## Last session" in state_text:
        pre, _ = state_text.split("## Last session", 1)
        return pre.rstrip() + "\n\n## Last session\n\n" + new_body + "\n"
    # No prior "Last session" — append
    if not state_text.endswith("\n"):
        state_text += "\n"
    return state_text + "\n## Last session\n\n" + new_body + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", default=str(DEFAULT_VAULT), help="vault root (default: %(default)s)")
    ap.add_argument(
        "--shipped",
        default=None,
        help="path (relative to vault) of the note that just shipped — updates 'Last session'",
    )
    ap.add_argument("--dry-run", action="store_true", help="print result, do not write")
    args = ap.parse_args()

    vault = Path(args.vault).expanduser().resolve()
    if not vault.exists():
        print(f"[fail] vault not found: {vault}", file=sys.stderr)
        return 2

    state_path = vault / "state" / "current.md"
    if not state_path.exists():
        print(f"[fail] state file missing: {state_path}", file=sys.stderr)
        return 2

    state_text = state_path.read_text(encoding="utf-8")
    new_coverage = build_coverage_block(vault)
    new_method = build_method_block(vault)

    updated = upsert_coverage_block(state_text, new_coverage)
    updated = upsert_method_block(updated, new_method)
    if args.shipped:
        today = date.today().isoformat()
        updated = rewrite_last_session(updated, args.shipped, today)

    if args.dry_run:
        sys.stdout.write(updated)
        return 0

    if updated == state_text:
        print("[ok]  state/current.md already up-to-date (no changes)")
        return 0

    state_path.write_text(updated, encoding="utf-8")
    print(f"[ok]  state/current.md rewritten ({len(updated)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
