import { Link } from "react-router-dom";
import { Shield, FileText } from "lucide-react";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <div className="max-w-3xl mx-auto px-4 py-16 space-y-10">

        {/* Header */}
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-zinc-500 text-sm">
            <FileText className="w-4 h-4" />
            <span>Legal</span>
          </div>
          <h1 className="text-3xl md:text-4xl font-black tracking-tight">Privacy Policy</h1>
          <p className="text-zinc-400 text-sm">Last updated: June 2026</p>
          <div className="flex flex-wrap gap-3 text-sm pt-1">
            <Link to="/" className="text-blue-400 hover:text-blue-300 underline underline-offset-2">
              Back to app
            </Link>
            <span className="text-zinc-700">·</span>
            <Link to="/terms" className="text-blue-400 hover:text-blue-300 underline underline-offset-2">
              Terms of Service
            </Link>
          </div>
        </div>

        {/* Privacy commitment callout */}
        <div className="bg-blue-950/30 border border-blue-500/30 rounded-2xl p-5 flex gap-4">
          <Shield className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
          <p className="text-blue-200/80 text-sm leading-relaxed">
            BMG Capital does not sell your data to third parties. We collect only what is necessary
            to provide and improve the paper trading service. No financial account credentials or
            real money are ever involved.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8 text-sm leading-relaxed text-zinc-300">

          <Section number="1" title="What We Collect">
            <p>
              We collect information you provide directly and information generated by your use of
              the Service. Here is a plain-English breakdown:
            </p>

            <SubSection title="Account information">
              <p>
                When you register, we collect your email address and chosen username. We do not
                collect your real name, phone number, or physical address unless you voluntarily
                provide them. No payment card data is stored on our servers — subscription billing
                is handled directly by Stripe (see Third-Party Services below).
              </p>
            </SubSection>

            <SubSection title="Paper trading activity">
              <p>
                We store all simulated trading data you generate on the platform, including
                simulated trades, bot configurations and logs, strategy selections and backtest
                results, portfolio snapshots, watchlists, alert rules, and trading journal entries.
                This data is yours and is used to power your experience across sessions and devices.
              </p>
            </SubSection>

            <SubSection title="Usage analytics">
              <p>
                We collect aggregated usage data to understand how the Service is used and to
                improve it. This includes pages visited, features used, session duration, and
                interaction patterns. Usage data is associated with your account but is not
                shared with third parties in individually identifiable form.
              </p>
            </SubSection>

            <SubSection title="What we do not collect">
              <p>
                We do not collect or store real financial account numbers, brokerage credentials,
                bank account information, Social Security numbers, government-issued ID, or any
                other sensitive financial data. BMG Capital is a paper trading platform — no real
                money ever flows through our systems.
              </p>
            </SubSection>
          </Section>

          <Section number="2" title="How We Use It">
            <p>We use the information we collect for the following purposes:</p>
            <ul className="mt-3 space-y-2 list-none">
              {[
                {
                  label: "To provide the Service:",
                  detail:
                    "Authenticating your account, storing and retrieving your paper trading data, running simulated strategies, and delivering AI-assisted features.",
                },
                {
                  label: "To improve the Service:",
                  detail:
                    "Analyzing usage patterns to identify bugs, usability issues, and feature opportunities. We may use anonymized, aggregated data in product research.",
                },
                {
                  label: "To communicate with you:",
                  detail:
                    "Sending transactional emails such as account confirmations, security alerts, and receipts. Sending product updates and feature announcements only with your consent (you can opt out at any time).",
                },
                {
                  label: "To detect abuse and maintain security:",
                  detail:
                    "Identifying suspicious activity, rate-limit violations, multi-account abuse, or attempts to reverse-engineer the platform.",
                },
                {
                  label: "To fulfill legal obligations:",
                  detail:
                    "Complying with applicable laws, responding to lawful requests from authorities, and enforcing our Terms of Service.",
                },
              ].map(({ label, detail }) => (
                <li key={label} className="flex items-start gap-2">
                  <span className="text-zinc-600 mt-0.5 shrink-0">—</span>
                  <span>
                    <span className="font-medium text-zinc-200">{label}</span> {detail}
                  </span>
                </li>
              ))}
            </ul>
          </Section>

          <Section number="3" title="Data Storage">
            <p>
              Your data is stored securely in Railway cloud infrastructure using encrypted storage
              at rest and in transit. We apply industry-standard security practices including access
              controls, audit logging, and regular security reviews.
            </p>
            <p className="mt-3">
              <span className="font-medium text-zinc-200">Your paper trading data is yours.</span>{" "}
              You can request a full export of your account data — including trades, journal
              entries, strategy configurations, and bot logs — at any time by contacting{" "}
              <a href="mailto:privacy@bmgcapital.com" className="text-blue-400 hover:text-blue-300 underline">
                privacy@bmgcapital.com
              </a>
              . We will provide the export in a machine-readable format within 30 days.
            </p>
            <p className="mt-3">
              We do not sell, rent, trade, or share your personal data with third parties for
              advertising or marketing purposes. Period.
            </p>
          </Section>

          <Section number="4" title="Cookies and Local Storage">
            <p>
              BMG Capital uses browser{" "}
              <span className="font-medium text-zinc-200">localStorage</span> — not cookies — to
              store your session token after login. This token is used to authenticate your API
              requests and keep you logged in across page loads. The token expires automatically and
              is cleared when you log out.
            </p>
            <p className="mt-3">
              We may also use localStorage to cache market data, UI preferences (such as theme and
              density settings), and query results on your device to improve performance.
            </p>
            <p className="mt-3">
              We do not use third-party advertising cookies. We do not participate in behavioral
              advertising networks or sell targeting data to advertisers.
            </p>
          </Section>

          <Section number="5" title="Third-Party Services">
            <p>
              We integrate with the following third-party services to power specific features. Each
              service has its own privacy policy governing how it handles data.
            </p>
            <div className="mt-4 space-y-4">
              {[
                {
                  name: "Alpaca Markets",
                  purpose: "Market data feed",
                  detail:
                    "Alpaca provides simulated market data (prices, bars, and quotes) that powers the paper trading engine. We do not share your personal account information with Alpaca.",
                },
                {
                  name: "Stripe",
                  purpose: "Subscription billing",
                  detail:
                    "Stripe processes subscription payments for Pro and Pro+ plans. When you add a payment method, that data is transmitted directly to Stripe and governed by Stripe's Privacy Policy. BMG Capital does not store your card number, CVV, or full billing details.",
                },
                {
                  name: "Anthropic",
                  purpose: "AI analysis features",
                  detail:
                    "Anthropic's Claude model powers AI Co-Pilot, AI Analyst, and related features. Queries are processed server-side — your request text is sent to Anthropic's API but is not associated with your personally identifiable information. Anthropic's API data usage policies apply.",
                },
                {
                  name: "Resend",
                  purpose: "Transactional email",
                  detail:
                    "Resend delivers account-related emails (confirmations, alerts, receipts). Your email address is shared with Resend solely for the purpose of sending those messages.",
                },
              ].map(({ name, purpose, detail }) => (
                <div key={name} className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-semibold text-zinc-200">{name}</span>
                    <span className="text-xs text-zinc-600 bg-zinc-800 px-2 py-0.5 rounded-full">
                      {purpose}
                    </span>
                  </div>
                  <p className="text-zinc-400">{detail}</p>
                </div>
              ))}
            </div>
          </Section>

          <Section number="6" title="Your Rights">
            <p>You have the following rights with respect to your personal data:</p>
            <ul className="mt-3 space-y-2 list-none">
              {[
                {
                  right: "Right to access:",
                  detail:
                    "Request a copy of all personal data we hold about you. We will provide it within 30 days.",
                },
                {
                  right: "Right to export:",
                  detail:
                    "Request your paper trading data in a machine-readable format (JSON or CSV). Contact privacy@bmgcapital.com.",
                },
                {
                  right: "Right to deletion:",
                  detail:
                    "Request deletion of your account and all associated personal data. We will complete the deletion within 30 days, subject to any data we are required to retain by law.",
                },
                {
                  right: "Right to opt out of emails:",
                  detail:
                    "Unsubscribe from non-transactional emails at any time via the unsubscribe link in any marketing email or by updating your notification preferences in Settings.",
                },
                {
                  right: "Right to correction:",
                  detail:
                    "Request correction of inaccurate personal data we hold about you.",
                },
              ].map(({ right, detail }) => (
                <li key={right} className="flex items-start gap-2">
                  <span className="text-zinc-600 mt-0.5 shrink-0">—</span>
                  <span>
                    <span className="font-medium text-zinc-200">{right}</span> {detail}
                  </span>
                </li>
              ))}
            </ul>
            <p className="mt-4">
              To exercise any of these rights, contact{" "}
              <a href="mailto:privacy@bmgcapital.com" className="text-blue-400 hover:text-blue-300 underline">
                privacy@bmgcapital.com
              </a>
              . We will respond within 30 days. We may ask you to verify your identity before
              fulfilling a request.
            </p>
          </Section>

          <Section number="7" title="Contact">
            <p>
              If you have questions, concerns, or requests regarding this Privacy Policy or your
              personal data, please contact our privacy team:
            </p>
            <div className="mt-4 bg-zinc-900 border border-zinc-800 rounded-xl p-5 space-y-1">
              <p className="font-semibold text-zinc-200">BMG Capital — Privacy</p>
              <p>
                Email:{" "}
                <a
                  href="mailto:privacy@bmgcapital.com"
                  className="text-blue-400 hover:text-blue-300 underline"
                >
                  privacy@bmgcapital.com
                </a>
              </p>
            </div>
          </Section>

        </div>

        {/* Footer nav */}
        <div className="border-t border-zinc-800 pt-8 flex flex-wrap gap-4 text-sm text-zinc-500">
          <Link to="/" className="hover:text-zinc-300 transition-colors">
            Back to BMG Capital
          </Link>
          <span>·</span>
          <Link to="/terms" className="hover:text-zinc-300 transition-colors">
            Terms of Service
          </Link>
          <span>·</span>
          <a href="mailto:privacy@bmgcapital.com" className="hover:text-zinc-300 transition-colors">
            privacy@bmgcapital.com
          </a>
        </div>

      </div>
    </div>
  );
}

function Section({
  number,
  title,
  children,
}: {
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-0">
      <h2 className="text-base font-bold text-white mb-3">
        <span className="text-zinc-600 font-normal mr-2">{number}.</span>
        {title}
      </h2>
      <div className="text-zinc-300">{children}</div>
    </section>
  );
}

function SubSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-4">
      <h3 className="text-sm font-semibold text-zinc-200 mb-1">{title}</h3>
      {children}
    </div>
  );
}
