"""
Seed 60 Track 1 exam questions into exam_questions table.
Track 1 — "The BMG Stack": BMG Capital approach, IMCP curriculum,
market analysis, trading philosophy, risk management, portfolio theory.

Idempotent — skips rows that already exist (checks by body hash or count).
Returns count of inserted rows.
"""
from __future__ import annotations

import logging
from sqlalchemy.orm import Session

from app.db.models.exams import ExamQuestion

logger = logging.getLogger(__name__)

_TRACK_SLUG = "track-1-the-bmg-stack"

# fmt: off
_QUESTIONS: list[dict] = [
    # ── Multiple Choice (40) ──────────────────────────────────────────────────
    {
        "body": "What is the primary purpose of the BMG Capital platform?",
        "question_type": "mc",
        "options": [
            "Execute live trades on behalf of users automatically",
            "Close the gap between institutional-grade investment tools and retail investors",
            "Provide social media features for traders to share tips",
            "Replace traditional brokerage accounts",
        ],
        "correct_answer": "1",
        "explanation": "BMG Capital exists to close the gap between institutional-grade investment tools and what individual investors have historically had access to.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
    {
        "body": "Which tool in the BMG platform would you use to filter stocks by P/E ratio below 15 and market cap above $1B?",
        "question_type": "mc",
        "options": ["Chart", "Screener", "Research", "Watchlist"],
        "correct_answer": "1",
        "explanation": "The Screener allows you to filter the entire investable universe by any combination of fundamental and technical criteria.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
    {
        "body": "In the IMCP Learning Center, what does IMCP stand for?",
        "question_type": "mc",
        "options": [
            "Integrated Market Capital Program",
            "Investment Management Competency Program",
            "International Markets Certification Protocol",
            "Interactive Model Construction Platform",
        ],
        "correct_answer": "1",
        "explanation": "IMCP stands for Investment Management Competency Program — structured curriculum from first principles to CFA/ACG exam readiness.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
    {
        "body": "What is the primary use of the Trade Journal feature?",
        "question_type": "mc",
        "options": [
            "Automating entry and exit orders",
            "Logging entries, exits, thesis, and post-mortems for review",
            "Displaying real-time price alerts",
            "Connecting to external brokerage accounts",
        ],
        "correct_answer": "1",
        "explanation": "The Trade Journal is a structured log for recording entries, exits, thesis, and post-mortems. Honest review of decisions is the highest-ROI habit in trading.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
    {
        "body": "Which of the following best describes a 'systematic' investment strategy?",
        "question_type": "mc",
        "options": [
            "One that relies on gut feeling and market intuition",
            "One based on defined rules for entry, sizing, and exit applied consistently",
            "One that only invests in index funds",
            "One managed exclusively by algorithms without human oversight",
        ],
        "correct_answer": "1",
        "explanation": "A systematic strategy is driven by predefined rules for entry, position sizing, and exit logic, applied consistently regardless of emotion.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 2,
    },
    {
        "body": "What does RSI stand for in technical analysis?",
        "question_type": "mc",
        "options": [
            "Rate of Stock Increase",
            "Relative Strength Index",
            "Risk Sensitivity Indicator",
            "Relative Sector Index",
        ],
        "correct_answer": "1",
        "explanation": "RSI (Relative Strength Index) is a momentum oscillator measuring the speed and magnitude of price changes, typically on a 0–100 scale.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "An RSI reading above 70 generally signals that a stock is:",
        "question_type": "mc",
        "options": [
            "Oversold and likely to rebound",
            "Overbought and potentially due for a pullback",
            "In a confirmed uptrend with momentum",
            "Moving sideways with no clear direction",
        ],
        "correct_answer": "1",
        "explanation": "RSI above 70 is traditionally considered overbought, suggesting the asset may be overextended and could face selling pressure.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "What does MACD stand for?",
        "question_type": "mc",
        "options": [
            "Moving Average Convergence Divergence",
            "Market Adjusted Capital Distribution",
            "Momentum And Crossover Detection",
            "Multi-Asset Correlation Denominator",
        ],
        "correct_answer": "0",
        "explanation": "MACD is Moving Average Convergence Divergence — a trend-following momentum indicator using the difference between two exponential moving averages.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "A bearish MACD crossover occurs when:",
        "question_type": "mc",
        "options": [
            "The MACD line crosses above the signal line",
            "The MACD line crosses below the signal line",
            "Both lines converge at zero",
            "Volume spikes on a down day",
        ],
        "correct_answer": "1",
        "explanation": "A bearish MACD crossover — the MACD line crossing below the signal line — is interpreted as a potential sell signal.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Bollinger Bands expand (widen) when:",
        "question_type": "mc",
        "options": [
            "Price is in a tight consolidation range",
            "Market volatility increases",
            "Trading volume decreases significantly",
            "The stock approaches a moving average",
        ],
        "correct_answer": "1",
        "explanation": "Bollinger Bands are based on standard deviations. Higher volatility causes the bands to expand; lower volatility causes them to contract (squeeze).",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Which time horizon best describes a 'swing trade'?",
        "question_type": "mc",
        "options": [
            "Seconds to minutes within a single day",
            "Days to weeks, capturing short-term price moves",
            "Months to years for long-term appreciation",
            "Decades, as used in retirement accounts",
        ],
        "correct_answer": "1",
        "explanation": "Swing trading typically holds positions for days to weeks, aiming to capture price swings in either direction.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "Support levels in technical analysis represent:",
        "question_type": "mc",
        "options": [
            "Price zones where selling pressure historically overcomes buying",
            "Price zones where buying pressure historically overcomes selling",
            "The average price over a given period",
            "Points where volume peaks occur",
        ],
        "correct_answer": "1",
        "explanation": "Support is a price level where demand is strong enough to prevent further decline — historically, buyers step in at these levels.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "A 'head and shoulders' pattern is generally considered:",
        "question_type": "mc",
        "options": [
            "A bullish continuation pattern",
            "A bearish reversal pattern",
            "A neutral consolidation pattern",
            "A bullish breakout pattern",
        ],
        "correct_answer": "1",
        "explanation": "The head and shoulders is a classic bearish reversal pattern indicating that an uptrend may be ending.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "What is the primary purpose of a stop-loss order?",
        "question_type": "mc",
        "options": [
            "To guarantee a profit when price reaches a target",
            "To limit maximum loss by exiting a position at a pre-set price",
            "To increase position size when price moves favorably",
            "To lock in unrealized gains indefinitely",
        ],
        "correct_answer": "1",
        "explanation": "A stop-loss order automatically exits a position if price falls to a specified level, capping the downside risk on a trade.",
        "module_slug": "risk-management",
        "difficulty": 1,
    },
    {
        "body": "The risk-reward ratio of a trade is calculated as:",
        "question_type": "mc",
        "options": [
            "Potential profit divided by the probability of success",
            "Potential loss divided by potential profit",
            "Distance to stop-loss divided by distance to price target",
            "Portfolio size divided by trade size",
        ],
        "correct_answer": "2",
        "explanation": "Risk-reward ratio = distance to stop (risk) / distance to target (reward). A 1:3 ratio means you risk $1 to potentially make $3.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "Position sizing in risk management refers to:",
        "question_type": "mc",
        "options": [
            "The number of different stocks in a portfolio",
            "Determining how much capital to allocate to a single trade",
            "The total market capitalization of your holdings",
            "The ratio of long to short positions",
        ],
        "correct_answer": "1",
        "explanation": "Position sizing determines how much of your capital to risk on any single trade, usually expressed as a percentage of total portfolio value.",
        "module_slug": "risk-management",
        "difficulty": 1,
    },
    {
        "body": "Diversification primarily reduces which type of risk?",
        "question_type": "mc",
        "options": [
            "Systematic (market) risk",
            "Unsystematic (company-specific) risk",
            "Interest rate risk",
            "Inflation risk",
        ],
        "correct_answer": "1",
        "explanation": "Diversification reduces unsystematic (idiosyncratic) risk — the risk specific to individual companies or sectors — but cannot eliminate systematic market risk.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "A portfolio's beta measures:",
        "question_type": "mc",
        "options": [
            "The total return of the portfolio over a given period",
            "The portfolio's sensitivity to overall market movements",
            "The maximum drawdown experienced in the past year",
            "The ratio of winning trades to losing trades",
        ],
        "correct_answer": "1",
        "explanation": "Beta measures a portfolio's volatility relative to the market. A beta of 1.5 means the portfolio typically moves 1.5% for every 1% market move.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "The Sharpe Ratio measures:",
        "question_type": "mc",
        "options": [
            "Total return minus benchmark return",
            "Risk-adjusted return: excess return per unit of total risk (standard deviation)",
            "The percentage of winning trades in a strategy",
            "Annualized volatility of returns",
        ],
        "correct_answer": "1",
        "explanation": "Sharpe Ratio = (Portfolio Return - Risk-Free Rate) / Standard Deviation. Higher values indicate better risk-adjusted performance.",
        "module_slug": "risk-management",
        "difficulty": 3,
    },
    {
        "body": "Maximum drawdown is defined as:",
        "question_type": "mc",
        "options": [
            "The largest single-day loss in a portfolio's history",
            "The peak-to-trough decline in portfolio value before a new peak is reached",
            "The average loss across all losing trades",
            "Annual portfolio return subtracted from a benchmark",
        ],
        "correct_answer": "1",
        "explanation": "Maximum drawdown is the largest peak-to-trough percentage decline — an important measure of downside risk and recovery potential.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "Modern Portfolio Theory (MPT), developed by Harry Markowitz, primarily argues that:",
        "question_type": "mc",
        "options": [
            "Individual stock selection is more important than asset allocation",
            "An optimal portfolio maximizes expected return for a given level of risk through diversification",
            "Investors should always hold 100% equities for maximum long-term growth",
            "Market timing is the primary driver of portfolio performance",
        ],
        "correct_answer": "1",
        "explanation": "MPT demonstrates that a diversified portfolio can achieve a higher expected return for any given risk level — the 'efficient frontier' concept.",
        "module_slug": "portfolio-theory",
        "difficulty": 3,
    },
    {
        "body": "The efficient frontier in portfolio theory represents:",
        "question_type": "mc",
        "options": [
            "Portfolios with the lowest possible risk regardless of return",
            "The set of portfolios offering maximum expected return for each level of risk",
            "The historical performance curve of the S&P 500",
            "A threshold where leverage becomes optimal",
        ],
        "correct_answer": "1",
        "explanation": "The efficient frontier is the curve of optimal portfolios — those offering the highest expected return for a given level of standard deviation.",
        "module_slug": "portfolio-theory",
        "difficulty": 3,
    },
    {
        "body": "Asset correlation of -1.0 between two assets means they:",
        "question_type": "mc",
        "options": [
            "Move in the same direction with equal magnitude",
            "Move in perfectly opposite directions — when one rises, the other falls equally",
            "Have no relationship to each other's price movements",
            "Both track the same benchmark index",
        ],
        "correct_answer": "1",
        "explanation": "A correlation of -1.0 means the assets move in perfectly opposite directions, providing the maximum diversification benefit when combined.",
        "module_slug": "portfolio-theory",
        "difficulty": 2,
    },
    {
        "body": "Dollar-cost averaging (DCA) is a strategy where:",
        "question_type": "mc",
        "options": [
            "You invest the maximum capital at the single best entry point",
            "You invest a fixed dollar amount at regular intervals regardless of price",
            "You buy more shares when prices rise to capture momentum",
            "You allocate capital based on each asset's market capitalization",
        ],
        "correct_answer": "1",
        "explanation": "DCA involves investing a fixed amount at regular intervals, which automatically buys more shares when prices are low and fewer when prices are high.",
        "module_slug": "portfolio-theory",
        "difficulty": 1,
    },
    {
        "body": "What does 'rebalancing' a portfolio mean?",
        "question_type": "mc",
        "options": [
            "Adding new funds to the portfolio monthly",
            "Selling winning assets and buying laggards to restore target allocations",
            "Switching from growth stocks to value stocks during downturns",
            "Increasing cash holdings during bear markets",
        ],
        "correct_answer": "1",
        "explanation": "Rebalancing restores a portfolio to its target asset allocation by trimming overweighted positions and adding to underweighted ones.",
        "module_slug": "portfolio-theory",
        "difficulty": 2,
    },
    {
        "body": "Price-to-Earnings (P/E) ratio is calculated as:",
        "question_type": "mc",
        "options": [
            "Net income divided by total revenue",
            "Stock price divided by earnings per share",
            "Market cap divided by book value",
            "Revenue divided by number of shares outstanding",
        ],
        "correct_answer": "1",
        "explanation": "P/E = Price per Share / Earnings per Share. It tells investors how much they pay for each dollar of earnings.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "Which financial statement shows a company's revenues and expenses over a period?",
        "question_type": "mc",
        "options": [
            "Balance Sheet",
            "Income Statement (Profit & Loss Statement)",
            "Cash Flow Statement",
            "Statement of Shareholders' Equity",
        ],
        "correct_answer": "1",
        "explanation": "The Income Statement (P&L) reports revenues, costs, and expenses over a specific accounting period, resulting in net income or loss.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "Free Cash Flow (FCF) is calculated as:",
        "question_type": "mc",
        "options": [
            "Net Income + Depreciation",
            "Operating Cash Flow minus Capital Expenditures",
            "Revenue minus Cost of Goods Sold",
            "EBITDA minus Interest Expense",
        ],
        "correct_answer": "1",
        "explanation": "FCF = Operating Cash Flow - CapEx. It represents the cash a company generates after maintaining or expanding its asset base.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "A moving average crossover strategy typically signals a buy when:",
        "question_type": "mc",
        "options": [
            "The short-term MA crosses below the long-term MA",
            "The short-term MA crosses above the long-term MA",
            "Price falls below both moving averages",
            "Volume drops below the 20-day average",
        ],
        "correct_answer": "1",
        "explanation": "A 'golden cross' — the short-term MA crossing above the long-term MA — is a classic bullish signal in trend-following strategies.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Which of the following describes 'backtesting' a trading strategy?",
        "question_type": "mc",
        "options": [
            "Simulating the strategy on future market conditions before going live",
            "Applying a strategy's rules to historical data to evaluate past performance",
            "Running multiple strategies simultaneously in live markets",
            "Reviewing trade journal entries for psychological patterns",
        ],
        "correct_answer": "1",
        "explanation": "Backtesting applies a strategy's rules to historical price data to see how it would have performed — a key step before live deployment.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 2,
    },
    {
        "body": "Earnings per Share (EPS) measures:",
        "question_type": "mc",
        "options": [
            "Revenue generated per outstanding share",
            "Net profit allocated to each outstanding share of common stock",
            "Dividends paid per share over the fiscal year",
            "Book value per share",
        ],
        "correct_answer": "1",
        "explanation": "EPS = Net Income / Shares Outstanding. It's one of the most widely followed metrics for assessing company profitability.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "A 'catalyst' in investment research typically refers to:",
        "question_type": "mc",
        "options": [
            "A technical pattern forming on the price chart",
            "An event or development that could cause a significant price change",
            "The overall market trend direction",
            "The trading volume spike in a stock",
        ],
        "correct_answer": "1",
        "explanation": "A catalyst is any event — earnings release, product launch, regulatory decision, macro shift — that could significantly change a stock's valuation.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "Value at Risk (VaR) represents:",
        "question_type": "mc",
        "options": [
            "The maximum possible loss over any time horizon",
            "The estimated maximum loss over a specific time period at a given confidence level",
            "The average daily loss of a portfolio",
            "The minimum return expected from a portfolio",
        ],
        "correct_answer": "1",
        "explanation": "VaR estimates the maximum expected loss over a given time frame at a specified confidence level (e.g., 95% or 99%).",
        "module_slug": "risk-management",
        "difficulty": 3,
    },
    {
        "body": "The Capital Asset Pricing Model (CAPM) is used to:",
        "question_type": "mc",
        "options": [
            "Calculate a company's intrinsic value using discounted cash flows",
            "Determine the expected return of an asset given its systematic risk (beta)",
            "Measure the profitability of individual business segments",
            "Evaluate credit risk in bond portfolios",
        ],
        "correct_answer": "1",
        "explanation": "CAPM determines expected return: E(R) = Risk-Free Rate + Beta × (Market Return - Risk-Free Rate). Beta captures systematic risk.",
        "module_slug": "portfolio-theory",
        "difficulty": 3,
    },
    {
        "body": "A 'paper trade' is best described as:",
        "question_type": "mc",
        "options": [
            "A trade executed via fax or mail order",
            "A simulated trade with no real money to practice strategy without risk",
            "A trade executed on the OTC (over-the-counter) market",
            "An institutional trade involving large block orders",
        ],
        "correct_answer": "1",
        "explanation": "Paper trading simulates trades with virtual money, allowing strategy testing and skill development without financial risk.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
    {
        "body": "Which of the following is a leading indicator in technical analysis?",
        "question_type": "mc",
        "options": [
            "Moving averages",
            "RSI (Relative Strength Index)",
            "200-day simple moving average",
            "Volume moving average",
        ],
        "correct_answer": "1",
        "explanation": "RSI is a leading (momentum-based) indicator that can signal potential reversals before they occur, unlike lagging indicators like moving averages.",
        "module_slug": "market-analysis",
        "difficulty": 3,
    },
    {
        "body": "Sector rotation refers to:",
        "question_type": "mc",
        "options": [
            "Rebalancing a portfolio to equal-weight all sectors",
            "The movement of institutional money between sectors based on the economic cycle",
            "Replacing domestic stocks with international ones periodically",
            "Shifting from equities to fixed income during recessions",
        ],
        "correct_answer": "1",
        "explanation": "Sector rotation describes how capital flows between sectors (e.g., from defensive to cyclical) as the economic cycle evolves.",
        "module_slug": "market-analysis",
        "difficulty": 3,
    },
    {
        "body": "The debt-to-equity ratio measures:",
        "question_type": "mc",
        "options": [
            "How much profit a company generates per dollar of equity",
            "The proportion of financing from debt versus shareholder equity",
            "The total liabilities minus total assets",
            "Revenue divided by total debt outstanding",
        ],
        "correct_answer": "1",
        "explanation": "D/E = Total Debt / Total Shareholders' Equity. It shows how leveraged a company is — high ratios signal more financial risk.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "In the context of the BMG Strategy Lab, 'paper mode' means:",
        "question_type": "mc",
        "options": [
            "Strategies are printed and reviewed manually",
            "Strategies trade using simulated capital with no real money at stake",
            "Strategies only run during market hours",
            "Strategies use historical data exclusively",
        ],
        "correct_answer": "1",
        "explanation": "Paper mode runs strategies with virtual capital, enabling users to evaluate bot performance and develop confidence before committing real funds.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
    {
        "body": "Return on Equity (ROE) is calculated as:",
        "question_type": "mc",
        "options": [
            "Net Income / Total Assets",
            "Net Income / Shareholders' Equity",
            "Operating Income / Revenue",
            "EBITDA / Total Debt",
        ],
        "correct_answer": "1",
        "explanation": "ROE = Net Income / Shareholders' Equity. It measures how efficiently management uses equity capital to generate profits.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Which of the following best describes 'alpha' in portfolio management?",
        "question_type": "mc",
        "options": [
            "The portfolio's total return over a year",
            "Returns generated in excess of the benchmark after adjusting for risk",
            "The volatility of the portfolio relative to the market",
            "The weighted average cost of capital",
        ],
        "correct_answer": "1",
        "explanation": "Alpha is the excess return relative to the expected return based on beta. Positive alpha means a manager added value beyond market compensation.",
        "module_slug": "portfolio-theory",
        "difficulty": 3,
    },

    # ── True / False (15) ─────────────────────────────────────────────────────
    {
        "body": "A higher P/E ratio always means a stock is overvalued.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "A high P/E may reflect high growth expectations rather than overvaluation. Context — industry norms, growth rate, competitive position — is essential.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Diversification can eliminate all investment risk in a portfolio.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "Diversification reduces unsystematic risk but cannot eliminate systematic (market) risk, which affects all assets simultaneously.",
        "module_slug": "risk-management",
        "difficulty": 1,
    },
    {
        "body": "The Sharpe Ratio adjusts portfolio return for the risk taken to achieve it.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "true",
        "explanation": "Sharpe Ratio = (Return - Risk-Free Rate) / Standard Deviation — it measures how much excess return you receive for each unit of risk.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "A stop-loss order guarantees execution at exactly the specified price.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "Stop-loss orders trigger at a specified price but execute at the next available market price, which can differ (slippage) in fast-moving markets.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "Backtesting a strategy on historical data guarantees future performance.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "Past performance does not guarantee future results. Backtests can suffer from overfitting, look-ahead bias, and changing market conditions.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 2,
    },
    {
        "body": "The income statement shows a company's financial position at a specific point in time.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "The balance sheet shows financial position at a point in time. The income statement covers revenues and expenses over a period of time.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "A beta greater than 1.0 indicates that a stock is more volatile than the overall market.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "true",
        "explanation": "Beta > 1.0 means the stock amplifies market moves — it tends to rise more than the market in up periods and fall more in down periods.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "Dollar-cost averaging eliminates market risk entirely.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "DCA reduces the impact of timing risk and price volatility but does not eliminate market risk — the investment can still decline in value.",
        "module_slug": "portfolio-theory",
        "difficulty": 1,
    },
    {
        "body": "Free Cash Flow is always equal to net income.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "FCF = Operating Cash Flow - CapEx, which differs from net income because it adjusts for non-cash items and capital expenditures.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "A portfolio on the efficient frontier cannot increase expected return without also increasing risk.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "true",
        "explanation": "The efficient frontier represents the optimal set of portfolios — moving to higher expected return requires accepting higher risk.",
        "module_slug": "portfolio-theory",
        "difficulty": 3,
    },
    {
        "body": "The head and shoulders chart pattern is considered a bullish continuation signal.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "Head and shoulders is a bearish reversal pattern, suggesting an uptrend is ending and a downtrend may follow.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Rebalancing a portfolio typically involves selling assets that have grown above target allocation.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "true",
        "explanation": "Rebalancing restores target allocation by trimming overweighted positions (selling winners) and adding to underweighted positions (buying laggards).",
        "module_slug": "portfolio-theory",
        "difficulty": 1,
    },
    {
        "body": "An RSI of 30 or below traditionally signals an oversold condition.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "true",
        "explanation": "RSI ≤ 30 is conventionally considered oversold, suggesting the asset may be undervalued and due for a potential rebound.",
        "module_slug": "market-analysis",
        "difficulty": 1,
    },
    {
        "body": "In CAPM, the market risk premium is calculated as the risk-free rate minus the expected market return.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "The market risk premium = Expected Market Return - Risk-Free Rate (not the other way around). It must be positive to incentivize investing in equities.",
        "module_slug": "portfolio-theory",
        "difficulty": 3,
    },
    {
        "body": "Systematic risk can be eliminated through diversification.",
        "question_type": "tf",
        "options": None,
        "correct_answer": "false",
        "explanation": "Systematic (market) risk affects all investments and cannot be diversified away. Only unsystematic (company-specific) risk can be reduced through diversification.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },

    # ── Short Answer (5) ──────────────────────────────────────────────────────
    {
        "body": "What two components are subtracted to calculate Free Cash Flow from operating cash flow?",
        "question_type": "sa",
        "options": None,
        "correct_answer": "capital expenditures",
        "explanation": "Free Cash Flow = Operating Cash Flow - Capital Expenditures (CapEx). CapEx represents investments in property, plant, and equipment.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "Name the chart pattern formed by a stock making a high, a higher high, and then a lower high — often signaling a bearish reversal.",
        "question_type": "sa",
        "options": None,
        "correct_answer": "head and shoulders",
        "explanation": "The head and shoulders pattern (left shoulder, head, right shoulder) is a classic bearish reversal formation on price charts.",
        "module_slug": "market-analysis",
        "difficulty": 2,
    },
    {
        "body": "What term describes the strategy of investing a fixed dollar amount at regular time intervals regardless of the asset's price?",
        "question_type": "sa",
        "options": None,
        "correct_answer": "dollar cost averaging",
        "explanation": "Dollar-cost averaging (DCA) reduces timing risk by spreading purchases over time, automatically buying more shares when prices are lower.",
        "module_slug": "portfolio-theory",
        "difficulty": 1,
    },
    {
        "body": "What is the name of the metric that measures a portfolio's excess return per unit of total risk (standard deviation)?",
        "question_type": "sa",
        "options": None,
        "correct_answer": "sharpe ratio",
        "explanation": "The Sharpe Ratio = (Portfolio Return - Risk-Free Rate) / Standard Deviation. It's the most widely used risk-adjusted performance metric.",
        "module_slug": "risk-management",
        "difficulty": 2,
    },
    {
        "body": "In the context of systematic strategies, what term describes the process of testing a strategy's rules against historical price data?",
        "question_type": "sa",
        "options": None,
        "correct_answer": "backtesting",
        "explanation": "Backtesting applies a strategy's rules to historical data to assess how it would have performed, helping identify strengths and weaknesses before live deployment.",
        "module_slug": "bmg-stack-intro",
        "difficulty": 1,
    },
]
# fmt: on


def seed_exam_questions(db: Session) -> int:
    """
    Insert exam questions into exam_questions table.
    Skips existing rows (idempotent by checking existing count and body).
    Returns count of rows actually inserted.
    """
    existing_bodies: set[str] = {
        row.body for row in db.query(ExamQuestion.body).all()
    }

    inserted = 0
    for q in _QUESTIONS:
        if q["body"] in existing_bodies:
            continue
        row = ExamQuestion(
            track_slug=_TRACK_SLUG,
            module_slug=q.get("module_slug"),
            question_type=q["question_type"],
            difficulty=q["difficulty"],
            body=q["body"],
            options=q.get("options"),
            correct_answer=q["correct_answer"],
            explanation=q["explanation"],
            is_active=True,
            tags=None,
            source_citation=None,
            numeric_tolerance=None,
            chart_image_url=None,
        )
        db.add(row)
        inserted += 1

    if inserted:
        db.commit()
        logger.info("[exam_seed] Inserted %d exam questions.", inserted)
    else:
        logger.info("[exam_seed] All questions already exist — skipping.")

    return inserted
