"""
Run v4 backtest through the hygiene gate.

REQUIRED before quoting any Ripper backtest number to Brock.

Wires:
  1. compute_signals_v4 → check_lookahead + check_recursive
  2. run_backtest_v4 → auto-haircut

Prints raw + haircut side-by-side so the user sees BOTH numbers and can never
be handed a naked +119R headline again.

Also writes the hygiene-gated result to vault: research/48-ripper-v4-hygiene-gated.md.
"""
import sys
from pathlib import Path
from datetime import datetime

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from ripper_v4 import compute_signals_v4, run_backtest_v4
from backtest_hygiene import run_hygiene_gate, compute_haircut

DATA_DIR = Path("/Users/brockgorzelanczyk/my-new-project/scripts/backtest/data")
VAULT_REPORT = Path("/Users/brockgorzelanczyk/Documents/BMG-Capital-Vault/research/48-ripper-v4-hygiene-gated.md")


def analyze(trades: pd.DataFrame):
    if len(trades) == 0:
        return {'n': 0, 'wr': 0.0, 'r': 0.0}
    n = len(trades)
    w = (trades['outcome'] == 'WIN').sum()
    l = (trades['outcome'] == 'LOSS').sum()
    wr = 100 * w / max(1, w + l)
    r = float(trades['r_multiple'].sum())
    return {'n': n, 'w': int(w), 'l': int(l), 'wr': float(wr), 'r': r}


def main():
    print("=" * 80)
    print("RIPPER v4 — HYGIENE-GATED BACKTEST")
    print("=" * 80)

    spy = pd.read_parquet(DATA_DIR / "spy_15m.parquet")
    vix = pd.read_parquet(DATA_DIR / "vix_daily.parquet")
    print(f"Loaded {len(spy):,} SPY 15m bars, {len(vix):,} VIX daily bars")

    print("\nRunning backtest first (need raw R for haircut math)...")
    signals, extras = compute_signals_v4(spy, vix)
    trades = run_backtest_v4(spy, signals, extras, use_regime_gates=True, use_trend_filter=True)
    stats = analyze(trades)
    print(f"  Raw: {stats['n']:,} trades, {stats['wr']:.1f}% WR, {stats['r']:+.1f}R")

    # Run the hygiene gate with raw stats
    passed, haircut_detail = run_hygiene_gate(
        compute_signals_v4,
        spy,
        vix,
        raw_r=stats['r'],
        n_trades=stats['n'],
        wr_pct=stats['wr'],
        avg_rr=1.5,
        declared_sizing_pct=5.0,
        in_sample_derived=True,          # regime rules + setup selection came from same 2018-2026 data
        execution_scenario="robinhood",  # BMG's actual broker
        years=8.5,
        strict=True,
    )

    # Also compute the same haircut so we can write it to vault
    hc = compute_haircut(
        raw_r=stats['r'],
        n_trades=stats['n'],
        wr_pct=stats['wr'],
        avg_rr=1.5,
        declared_sizing_pct=5.0,
        in_sample_derived=True,
        execution_scenario="robinhood",
        years=8.5,
    )

    # Write vault report
    print(f"\nWriting hygiene-gated report to {VAULT_REPORT}")
    banner = "✅ HYGIENE PASSED" if passed else "❌ HYGIENE FAILED — DO NOT QUOTE RAW"
    with open(VAULT_REPORT, "w") as f:
        f.write(f"---\ntitle: Ripper v4 — hygiene-gated backtest\ngenerated: {datetime.now().strftime('%Y-%m-%d %H:%M CT')}\n---\n\n")
        f.write(f"# 48 — Ripper v4 (hygiene-gated)\n\n")
        f.write(f"**Status:** {banner}\n\n")
        f.write("This file is auto-generated by `scripts/backtest/run_v4_with_hygiene.py`. It replaces the "
                "raw-only `research/30-ripper-v4-adaptive-regime-backtest.md` when quoting live expectation.\n\n")
        f.write("## Raw backtest (untreated — DO NOT quote in isolation)\n\n")
        f.write(f"| Metric | Value |\n|---|---|\n")
        f.write(f"| Trades | {stats['n']:,} |\n")
        f.write(f"| Win rate | {stats['wr']:.1f}% |\n")
        f.write(f"| Total R | {stats['r']:+.1f}R |\n")
        f.write(f"| Compound at 5% sizing | {hc.raw_end_compound_pct:+.0f}% |\n\n")

        f.write("## Hygiene haircut chain\n\n")
        f.write("Applied sequentially per `scripts/backtest/backtest_hygiene.py`:\n\n")
        f.write("```\n" + hc.detail + "\n```\n\n")

        f.write("## Realistic live expectation\n\n")
        f.write(f"| Metric | Value |\n|---|---|\n")
        f.write(f"| R (low) | {hc.realistic_r_low:+.1f}R |\n")
        f.write(f"| R (high) | {hc.realistic_r_high:+.1f}R |\n")
        f.write(f"| Kelly-safe sizing | {hc.kelly_safe_sizing_pct:.2f}% per trade |\n")
        f.write(f"| Annual CAGR (low) at Kelly-safe | {hc.realistic_annual_cagr_low*100:+.1f}% |\n")
        f.write(f"| Annual CAGR (high) at Kelly-safe | {hc.realistic_annual_cagr_high*100:+.1f}% |\n\n")

        f.write("## Why the haircuts\n\n")
        f.write("- **× 0.35 in-sample decay** — McLean-Pontiff 2016: strategies derived from the same\n"
                "  historical data they were later tested on realize 30-40% of backtested returns out-of-sample.\n"
                "  Ripper v4's regime gates + setup selection came from this same 2018-2026 data — worst case.\n\n")
        f.write("- **− 0.06R per trade execution drag** — per `research/36`: Robinhood market orders vs\n"
                "  quoted mid-price on 15m SPY options: ~2-4¢ slippage + 0.03-0.05R adverse fill.\n"
                "  Multiplied across the full trade count is a real cash number.\n\n")
        f.write("- **× 0.70 options P&L gap** — per `research/35` + Tastytrade 40k-trade sample:\n"
                "  long-premium options realize 60-75% of the underlying's R-model movement due to\n"
                "  IV crush, delta decay, and non-linear payoff at intermediate underlying prices.\n\n")

        f.write("## Sizing rule (Kelly-safe)\n\n")
        f.write(f"Recommended per-trade risk: **{hc.kelly_safe_sizing_pct:.2f}%** of account.\n\n")
        f.write("Rule from `research/35`: use min(quarter-Kelly, 1.5% hard cap). This trades some\n"
                "upside for survival — Kelly is optimal only if the win rate + payoff assumptions hold\n"
                "perfectly, which the hygiene haircuts explicitly say they will not.\n\n")

    print(f"\n✅ Done. See {VAULT_REPORT}")
    return stats, hc, passed


if __name__ == "__main__":
    main()
